/*

*/

global proc CleanWindow() {
	print "Found new version\n";
	if (`window -exists "Aassist"`){
		deleteUI -window "Aassist";
	}
	if( `dockControl -exists "AnimAssistantdock"` ){
		deleteUI "AnimAssistantdock";
	}
}


global proc AnimAssist () {
	global int $scriptVersion = 21;
	global string $window = "Aassist";
	global int $saveMWwidth;
	global string $history[];
	global string $historyStart[];
	global string $historyEnd[];
	$history = {};
	$historyStart = {};
	$historyEnd = {};
	$saveMWwidth = {};
	$ready = 0;
	string $dock = "AnimAssistantdock";
	if (`optionVar -ex AassistScriptVersion`){
		int $currentVersion = `optionVar -q AassistScriptVersion`;
		if ($scriptVersion != $currentVersion) {
			CleanWindow();
		}
	} else {
		CleanWindow();
	}
	optionVar -iv AassistScriptVersion $scriptVersion;
	$visibleDock = false;
	if (`window -exists $window`){
		// $saveMWwidth = `window -q -w $window`;
		window -e -visible true $window;
		$ready = 1;
	}
	if (windowExistsWithDock ($window)){
		window -e -visible true $window;
		$ready = 1;
	}
	if( `dockControl -exists $dock` ){
		$visibleDock = `dockControl -q -visible $dock`;
		dockControl -e -visible true $dock;
		$ready = 1;
	}
	if ($visibleDock){
		dockControl -e -visible false $dock;
	}
	if ($ready) {
		// UpdateCamerasList();
		updateAnims();
		return;
	}

	float $blue[];
	float $orange[];
	float $green[];
	float $red[];
	float $navRed[];
	float $navGreen[];
	float $navBlue[];

	/* ---START--- Color scheme, 0 - uncolored buttons, 1 - colored buttons // Цветовая схема, 0 - бесцветные кнопки, 1 - цветные кнопки ---НАЧАЛО--- */
	int $AnimColoredButtons = 0;
	/* ---END--- Color scheme, 0 - uncolored buttons, 1 - colored buttons // Цветовая схема, 0 - бесцветные кнопки, 1 - цветные кнопки ---КОНЕЦ--- */


	if ($AnimColoredButtons == 1){
		$blue = {0.0, 0.54, 1.0};
		$orange = {0.89, 0.392, 0.2156};
		$green = {0.407843, 0.631373, 0.188235};
		$red = {1.0, 0.2196, 0.0117};
		$navRed = {0.7, 0.2, 0.2};
		$navGreen = {0.2, 0.7, 0.2};
		$navBlue = {0.2, 0.2, 0.7};
	} else {
		$blue = {0.255, 0.539, 0.7012};
		$orange = {0.255, 0.539, 0.7012};
		$green = {0.255, 0.539, 0.7012};
		$red =  {0.255, 0.539, 0.7012};
		$navRed =  {0.255, 0.539, 0.7012};
		$navGreen =  {0.255, 0.539, 0.7012};
		$navBlue =  {0.255, 0.539, 0.7012};

	}


	string $windowTitle = "AnimAssistant";

	window -t $windowTitle -width 300 $window;

	scriptJob -e SceneOpened AnimLiUpdate;
	//scriptJob -e cameraChange UpdateCamerasList;

	string $pane = "myPane";
	/*---------------WINDOW DIVIDER------------------*/
	global string $AnimSep;

	$AnimSep = `paneLayout -smc "SepRemember" -configuration "horizontal2" -p $window $pane`;

	/*---------------WINDOW DIVIDER - Top main window------------------*/
	formLayout -p $pane  -w 243 -h 340 AnimAssistMainWindow;

	text -al "center"  -h 22  -l "Anim Manager" -ebg true -bgc 0 0 0 AnimManagerTitle;
	global string $animfl;
	$animfl = `textField -h 25 -w 213 -ann "filter" -cc "AnimFilter" -ec "AnimFilter" -p "AnimAssistMainWindow" -aie true AnimationFilterField`;
	popupMenu;
	menuItem -l "Filter" -c ( "AnimFilter" );
	menuItem -l "Clear" -c ( "ClearFlField" );

	global string $undoButton;
	$undoButton = `iconTextButton -w 20 -h 20 -style "iconOnly" -image "undo_icon_20" -c "UndoAction" -label "undo" undoButtonInstance`;

	global string $animli;
	$animli = `textScrollList -w 243 -h 10 -ams true -sc "SelectAnimClip" -dcc "FocusAnimClip" -dkc "RemoveAnimName" -p "AnimAssistMainWindow" animlister`;
	popupMenu;
	menuItem -l "Delete selected" -c ( "RemoveAnimName" );
	menuItem -l "Store takes" -c ( "StoreTakes" );
	menuItem -l "Export to GameExp" -c ( "ExptoTOGame" );
	menuItem -l "Export" -c ( "AnimExporter" );
	menuItem -l "Export Selected" -c ( "AnimExporterSelected" );
	menuItem -l "Import" -c ( "AnimImporter" );
	menuItem -l "Refresh list" -c ( "RefreshAnimList" );

	global string $animnm;
	$animnm = `textField  -h 25 -ann "animation name" -ec "AppendAnimName" -p "AnimAssistMainWindow" -aie true AnimationNameField`;
	popupMenu;
	menuItem -l "Edit" -c ( "RenNmField" );
	menuItem -l "Clear" -c ( "ClearNmField" );
	menuItem -l "Clear all" -c ( "ClearAllField" );
	formLayout -p "AnimAssistMainWindow"  -w 202 -h 28 AnimManButtons;
	button -backgroundColor  $blue[0] $blue[1] $blue[2]  -label "^" -w 25 -h 28 -c "moveAnimUP" -p "AnimManButtons" moveAnimUPbutton;
	button -backgroundColor  $blue[0] $blue[1] $blue[2]  -label "v" -w 25 -h 28 -c "moveAnimDN" -p "AnimManButtons" moveAnimDNbutton;
	button -backgroundColor  $orange[0] $orange[1] $orange[2]  -label "pick" -w 32 -h 28 -c "FrameInst" -p "AnimManButtons" FrameInstbutton;
	button -backgroundColor  $green[0] $green[1] $green[2] -label "+" -w 25 -h 28 -c "AppendAnimName" -p "AnimManButtons" AppendAnimNamebutton;
	button -backgroundColor  $red[0] $red[1] $red[2]  -label "-" -w 25 -h 28 -c "RemoveAnimName"  -p "AnimManButtons" RemoveAnimNamebutton;
	/*---------------Anim manager fields (START FRAME and END FRAME)------------------*/
	global string $framest;
	global string $frameen;
	global string $frameco;
	$framest = `textField -w 48 -h 25 -ann "start frame" -ec "AppendAnimName" -p "AnimManButtons" -aie true startframefield`;
	popupMenu;
	menuItem -l "Edit" -c ( "RenNmField" );
	menuItem -l "Clear" -c ( "ClearStField" );
	menuItem -l "Clear all" -c ( "ClearAllField" );
	$frameen = `textField -w 48 -h 25 -ann "end frame" -ec "AppendAnimName" -p "AnimManButtons" -aie true endframefield`;
	popupMenu;
	menuItem -l "Edit" -c ( "RenNmField");
	menuItem -l "Offset" -c ( "AnimOffset" );
	menuItem -l "Clear" -c ( "ClearEnField" );
	menuItem -l "Clear all" -c ( "ClearAllField" );
	$frameco = `text -al "center"  -h 22 -l " 0 " -p "AnimManButtons" countframefiled`;
	/*---------------Cameras frame START------------------*/
	formLayout -p $pane  -w 243 -h 340 AnimAssistBottomWindow;
	text -al "center"  -h 22 -l "Cameras" -ebg true -bgc 0 0 0 -p "AnimAssistBottomWindow" CamerasTitle;
	global string $camerasList;
	// $animli = `textScrollList -w 243 -h 10 -ams true -sc "SelectAnimClip" -dcc "FocusAnimClip" -dkc "RemoveAnimName" -p "AnimAssistMainWindow" animlister`;
	$camerasList = `textScrollList -w 243 -h 10 -ams true -dcc "SetCamera" -p "AnimAssistBottomWindow" cameraslister`;
	popupMenu;
	menuItem -l "Update Cameras" -c ( "UpdateCamerasList" );
	/*---------------Playblast frame START------------------*/
	text -al "center"  -h 22 -l "Playblast" -ebg true -bgc 0 0 0 -p "AnimAssistMainWindow" PlayblastTitle;
	global string $pbPath;
	$pbPath  = `textField -h 25 -ann "file path" -ec "PathEdPB" -cc "PathEdPB" -p "AnimAssistMainWindow" -aie true pathfield`;
	global string $ffmpegPath;
	$ffmpegPath  = `textField -h 25 -ann "ffmpeg path" -ec "PathEdFfmpeg" -cc "PathEdFfmpeg" -p "AnimAssistMainWindow" -aie true pathffmpegfield`;
	$ffmpegPathValue = `getenv "FFMPEG_PATH"`;
	textField -e -tx $ffmpegPathValue $ffmpegPath;
	global string $pbPrefix;
	$pbPrefix = `textField -w 70 -h 25 -ann "name prefix" -ec "PreEdPB" -cc "PreEdPB" -p "AnimAssistMainWindow" -aie true nameprefixfield`;
	popupMenu;
	menuItem -l "<= Paste frames" -c ( "PastePrePBSt" );
	menuItem -l "Paste frames =>" -c ( "PastePrePBEn" );

	global string $pbPostfix;
	$pbPostfix = `textField -w 70 -h 25 -ann "name postfix" -ec "PostEdPB" -cc "PostEdPB" -p "AnimAssistMainWindow" -aie true namepostfixfield`;
	popupMenu;
	menuItem -l "<= Paste frames" -c ( "PastePostPBSt" );
	menuItem -l "Paste frames =>" -c ( "PastePostPBEn" );
	button -backgroundColor  $orange[0] $orange[1] $orange[2]  -label "Browse" -w 72 -h 28 -c "BrowsePB"  -p "AnimAssistMainWindow" Browsebutton;
	button -backgroundColor  $orange[0] $orange[1] $orange[2]  -label "FFmpeg" -w 72 -h 28 -c "BrowseFfmpeg"  -p "AnimAssistMainWindow" BrowseFfmpegbutton;
	button -backgroundColor  $green[0] $green[1] $green[2] -label "Playblast" -w 52 -h 28 -c "PlayblastPB" -p "AnimAssistMainWindow" Playblastbutton;
	button -backgroundColor  $green[0] $green[1] $green[2] -label "(i)" -w 20 -h 28 -c "PlayblastConfig" -p "AnimAssistMainWindow" PlayblastbuttonConfig;
	text -al "center"  -h 22 -l "prefix | postfix" -p "AnimAssistMainWindow" PlayblastNameText;
	/*---------------Playblast------------------*/
	formLayout -edit -w 300 -h 28
		-af AnimManagerTitle left 0
		-af AnimManagerTitle right 0
		-af AnimManagerTitle top 0
		-ac AnimationFilterField top 2 AnimManagerTitle
		-af AnimationFilterField left 3
		-af AnimationFilterField right 25
		-ac undoButtonInstance top 2 AnimManagerTitle
		-af undoButtonInstance right 3
		-ac undoButtonInstance left 2 AnimationFilterField
		-ac undoButtonInstance bottom 3 animlister
		-ac animlister top 2 AnimationFilterField
		-af animlister left 2
		-af animlister right 2
		-ac animlister bottom 3 AnimationNameField
		-af AnimationNameField left 3
		-af AnimationNameField right 3
		-ac AnimationNameField bottom 3 AnimManButtons

		-af AnimManButtons left 3
		-ac AnimManButtons bottom 3 PlayblastTitle
		-af AnimManButtons right 3

		-af PlayblastTitle left 0
		-af PlayblastTitle right 0
		-ac PlayblastTitle bottom 0 nameprefixfield
		-ac PlayblastTitle bottom 0 PlayblastNameText
		-ac PlayblastTitle bottom 0 namepostfixfield
		-ac PlayblastTitle bottom 4 Playblastbutton
		-ac PlayblastTitle bottom 4 PlayblastbuttonConfig

		-af nameprefixfield left 2
		-ac nameprefixfield right 3 PlayblastNameText
		-ac nameprefixfield bottom 4 pathfield

		-ac PlayblastNameText bottom 6 pathfield
		-ac PlayblastNameText right 3 namepostfixfield

		-ac namepostfixfield right 3 Playblastbutton
		-ac namepostfixfield bottom 4 pathfield

		-ac Playblastbutton right 0 PlayblastbuttonConfig
		-ac Playblastbutton bottom 2 Browsebutton

		-af PlayblastbuttonConfig right 3	
		-ac PlayblastbuttonConfig bottom 2 Browsebutton

		-af pathfield left 2
		-ac pathfield bottom 5 pathffmpegfield
		-ac pathfield right 2 Browsebutton

		-af Browsebutton right 3
		-ac Browsebutton bottom 2 BrowseFfmpegbutton

		-af pathffmpegfield left 2
		-ac pathffmpegfield right 2 BrowseFfmpegbutton
		-af pathffmpegfield bottom 5

		-af BrowseFfmpegbutton bottom 3
		-af BrowseFfmpegbutton right 3

		AnimAssistMainWindow;

	formLayout -edit -w 300 -h 28
		-af CamerasTitle left 0
		-af CamerasTitle right 0
		-af CamerasTitle top 0
		-ac cameraslister top 3 CamerasTitle
		-af cameraslister left 2
		-af cameraslister right 2
		-af cameraslister bottom 3
		AnimAssistBottomWindow;

	formLayout -edit -w 300 -h 28
		-af moveAnimUPbutton bottom 0
		-ac moveAnimDNbutton left 2 moveAnimUPbutton
		-af moveAnimDNbutton bottom 0
		-ac FrameInstbutton left 2 moveAnimDNbutton
		-af FrameInstbutton bottom 0
		-ac AppendAnimNamebutton left 2 FrameInstbutton
		-af AppendAnimNamebutton bottom 0
		-ac RemoveAnimNamebutton left 2 AppendAnimNamebutton
		-af RemoveAnimNamebutton bottom 0
		-af startframefield bottom 2
		-ac startframefield left 2 RemoveAnimNamebutton
		-af endframefield bottom 2
		-ac endframefield left 2 startframefield
		-af countframefiled bottom 2
		-af countframefiled right 0
		-ac countframefiled left 6 endframefield
		AnimManButtons;

	window -edit -s true -widthHeight 246.0 341.0 $window;
	{

		string $dockSide = "left";
		int $dockFloating = 0;
		string $dockInfo[] = {};
		if (`optionVar -ex AAssistDock`) {
			$dockInfo = `optionVar -q AAssistDock`;
			$dockSide = $dockInfo[0];
			$dockFloating = $dockInfo[1];
		}
		if (`dockControl -ex $dock`) {
			deleteUI $dock;
		}
		{
			dockControl -aa right -aa left -area $dockSide -content $window -l "Anim Assistant" -fcc AAssistSavePosition -fl $dockFloating $dock;
		}
	}
	int $grex = `objExists "AnimAssistant"`;
	if ($grex == 1){
		string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($animlinm, " ");
		for ($bip in $animlinmarr) {
			textScrollList -e -a $bip $animli;
		}

		string $lstArrtA[] = `listAttr -ud AnimAssistant`;
		int $iPlayblastPt = stringArrayFind( "PlayblastPt", 0, $lstArrtA );
		if ($iPlayblastPt!=-1){
			string $PlayblastPtAttr = `getAttr AnimAssistant.PlayblastPt`;
			if($PlayblastPtAttr!=""){
				textField -e -tx $PlayblastPtAttr $pbPath;
			}
		}
		int $iPlayblastPost = stringArrayFind( "PlayblastPost", 0, $lstArrtA );
		if ($iPlayblastPost!=-1){
			string $PlayblastPostAttr = `getAttr AnimAssistant.PlayblastPost`;
			if($PlayblastPostAttr!=""){
				textField -e -tx $PlayblastPostAttr $pbPostfix;
			}
		}
		int $iPlayblastPre = stringArrayFind( "PlayblastPre", 0, $lstArrtA );
		if ($iPlayblastPre!=-1){
			string $PlayblastPreAttr = `getAttr AnimAssistant.PlayblastPre`;
			if($PlayblastPreAttr!=""){
				textField -e -tx $PlayblastPreAttr $pbPrefix;
			}
		}
	}
	UpdateCamerasList();
	global string $spa;
	$spa = "-worldSpace";
	if($saveMWwidth>0){
		optionVar -iv OsaveMWwidth $saveMWwidth;
		// window -e -w $saveMWwidth $window;
		// formLayout -e -w $saveMWwidth AnimAssistMainWindow;
		// dockControl -e -w $saveMWwidth $dock;
		// formLayout -e -w 248 AnimAssistMainWindow;
	} else {
		if (`optionVar -ex OsaveMWwidth`){
			int $OvarWidthW = `optionVar -q OsaveMWwidth`;
			// window -e -w $OvarWidthW $window;
			// formLayout -e -w $OvarWidthW AnimAssistMainWindow;
			// dockControl -e -w $OvarWidthW $dock;
			// formLayout -e -w 248 AnimAssistMainWindow;
		}
	}
	if (`optionVar -ex AAWin`){
		int $AAInfo[] = {};
		$AAInfo = `optionVar -q AAWin`;
		paneLayout -e -ps 1 100 $AAInfo[0] -ps 2 100 $AAInfo[1] $pane;
	}
	scriptJob -event "quitApplication" optawidth;
}


//////////////////////////////////////////////////////////////////////////////////////////////////

global proc updateAnims() {
	global string $animli;
	int $grex = `objExists "AnimAssistant"`;
	if ($grex == 1){
		textScrollList -e -ra $animli;
		string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($animlinm, " ");
		print("AnimAssistant check:\n");
		for ($bip in $animlinmarr) {
			textScrollList -e -a $bip $animli;
		}
	}
}

global proc UndoAction() {
	global string $history[];
	global string $historyStart[];
	global string $historyEnd[];
	global string $framest;
	global string $frameen;
	global string $animnm;
	global string $frameco;
	global string $animli;
	if (size($history) > 0) {
		int $indexSelected[] = `textScrollList -q -selectIndexedItem $animli`;
		string $animlinm = $history[size($history) - 1];
		stringArrayRemoveAtIndex(size($history) - 1, $history);
		string $animFrameStart = $historyStart[size($historyStart) - 1];
		stringArrayRemoveAtIndex(size($historyStart) - 1, $historyStart);
		string $animFrameEnd = $historyEnd[size($historyEnd) - 1];
		stringArrayRemoveAtIndex(size($historyEnd) - 1, $historyEnd);
		setAttr -type "string" AnimAssistant.AnimationClipName $animlinm;
		setAttr -type "string" AnimAssistant.StartFrame $animFrameStart;
		setAttr -type "string" AnimAssistant.EndFrame $animFrameEnd;
		AnimLiUpdate();
		if (size($indexSelected) > 0) {
			textScrollList -e -selectIndexedItem $indexSelected[0] $animli;
			SelectAnimClip();
		} else {
			textField -e -tx "" $framest;
			textField -e -tx "" $frameen;
			textField -e -tx "" $animnm;
			text -e -l "0" $frameco;
		}
	}
}

global proc AppendUndo() {
	global string $history[];
	global string $historyStart[];
	global string $historyEnd[];
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animFrameStart = `getAttr AnimAssistant.StartFrame`;
	string $animFrameEnd = `getAttr AnimAssistant.EndFrame`;
	if (size($history) > 0) {
		if ($history[size($history) - 1] == $animlinm) {
			return;
		}
	}
	stringArrayInsertAtIndex(size($history), $history, $animlinm);
	stringArrayInsertAtIndex(size($historyStart), $historyStart, $animFrameStart);
	stringArrayInsertAtIndex(size($historyEnd), $historyEnd, $animFrameEnd);
}

global proc string FindAnimationFullName(string $name) {
	if (size($name) < 5) return $name;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	for ($anim in $animlinmarr) {
		string $shortName = `substitute ($name + "_[0-9]*-[0-9]") $anim $name`;
		if ($shortName == $name) {
			return $anim;
		}
	}
	return $name;
}

global proc PlayblastConfig() {
	performPlayblast 4;
}

global proc SetCamera(){
	global string $camerasList;
	string $camerasSelected[] = `textScrollList -q -si $camerasList`;
	if (size($camerasSelected) != 0) {
		string $view = `getPanel -withFocus`;
		lookThru $camerasSelected[0] $view;
	}
}

global proc UpdateCamerasList() {
	global string $camerasList;
	textScrollList -e -removeAll $camerasList;
	string $orthoCameras[] = `listCameras`;
	for ($camera in $orthoCameras) {
		$visible = `getAttr ($camera + ".visibility")`;
		if ($visible == "1") {
			textScrollList -e -a $camera $camerasList;
		}
		// scriptJob -attributeChange ($camera + ".visibility") UpdateCamerasList;
	}
}

global proc UpdateCamera(string $camera) {

}

global proc optawidth(){
	AnimAssist;
}

global proc int floatToInt(float $float)
{
	int $int = $float;
	return $int;
}

global proc int mayaVersion()
{
	return (floatToInt(`getApplicationVersionAsFloat`));
}

global proc int windowExistsWithDock (string $window)
{
	string $dock = $window + "Dock";

	if (mayaVersion() >= 2011)
		{
		if (!`dockControl -q -ex $dock`)
			return 0;
		if (!`dockControl -q -vis $dock`)
			return 0;
		}

	int $num = forInNum ($window, `lsUI -wnd`);
	if ($num == -1)
		return 0;
	else
		return 1;
}

global proc AAssistSavePosition() {
	string $dock	= "AnimAssistantdock";
	if (!`dockControl -q -ex $dock`)
		return;
	optionVar -sv AAssistDock (`dockControl -q -a $dock`);
	optionVar -sva AAssistDock (`dockControl -q -fl $dock`);
}

/*--------------Remember separator position------------*/
global proc SepRemember(){
	global string $AnimSep;
	int $AAInfo[] = {};
	int $sepValue[] = `paneLayout -q -ps $AnimSep`;
	if($sepValue[1]<80){
		optionVar -iv AAWin ($sepValue[1]);
		optionVar -iva AAWin ($sepValue[3]);
	} else {
		optionVar -iv AAWin 100;
		optionVar -iva AAWin 0;
	}
}

global proc CreateIfNotExistNodeAttribute() {
	int $grex = `objExists "AnimAssistant"`;
	if ($grex == 0){
		createNode "geometryVarGroup" -ss -n "AnimAssistant";
		addAttr -dt "string" -longName "AnimationClipName" AnimAssistant;
		addAttr -dt "string" -longName "StartFrame" AnimAssistant;
		addAttr -dt "string" -longName "EndFrame" AnimAssistant;
		addAttr -dt "string" -longName "PlayblastPt" AnimAssistant;
		addAttr -dt "string" -longName "PlayblastPost" AnimAssistant;
		addAttr -dt "string" -longName "PlayblastPre" AnimAssistant;
	}
}


/*---------------Playblast Path -------------*/
global proc BrowsePB(){
	global string $pbPath;
	CreateIfNotExistNodeAttribute();
	string $lstArrtA[] = `listAttr -ud AnimAssistant`;
	int $iPlayblastPt = stringArrayFind( "PlayblastPt", 0, $lstArrtA );
	if ($iPlayblastPt==-1){
		addAttr -dt "string" -longName "PlayblastPt" AnimAssistant;
	}
	int $iPlayblastPost = stringArrayFind( "PlayblastPost", 0, $lstArrtA );
	if ($iPlayblastPost==-1){
		addAttr -dt "string" -longName "PlayblastPost" AnimAssistant;
	}
	int $iPlayblastPre = stringArrayFind( "PlayblastPre", 0, $lstArrtA );
	if ($iPlayblastPre==-1){
		addAttr -dt "string" -longName "PlayblastPre" AnimAssistant;
	}
	string $result[] = `fileDialog2 -fm 3`;

	setAttr -type "string" AnimAssistant.PlayblastPt ($result[0]);

	textField -e -tx $result[0] $pbPath;
}

global proc BrowseFfmpeg(){
	global string $ffmpegPath;
	string $result[] = `fileDialog2 -fm 3`;
	
	putenv "FFMPEG_PATH" $result[0];

	textField -e -tx $result[0] $ffmpegPath;
}

global proc PathEdFfmpeg(){
	global string $ffmpegPath;
	string $getPath = `textField -q -tx $ffmpegPath`;
	putenv "FFMPEG_PATH" $getPath;
}

global proc PathEdPB(){
	global string $pbPath;
	string $getPath = `textField -q -tx $pbPath`;
	CreateIfNotExistNodeAttribute();
	string $lstArrtA[] = `listAttr -ud AnimAssistant`;
	int $iPlayblastPt = stringArrayFind( "PlayblastPt", 0, $lstArrtA );
	if ($iPlayblastPt==-1){
		addAttr -dt "string" -longName "PlayblastPt" AnimAssistant;
	}
	int $iPlayblastPost = stringArrayFind( "PlayblastPost", 0, $lstArrtA );
	if ($iPlayblastPost==-1){
		addAttr -dt "string" -longName "PlayblastPost" AnimAssistant;
	}
	int $iPlayblastPre = stringArrayFind( "PlayblastPre", 0, $lstArrtA );
	if ($iPlayblastPre==-1){
		addAttr -dt "string" -longName "PlayblastPre" AnimAssistant;
	}
	setAttr -type "string" AnimAssistant.PlayblastPt ($getPath);
}

global proc PreEdPB(){
	global string $pbPrefix;
	string $preField = `textField -q -tx $pbPrefix`;
	CreateIfNotExistNodeAttribute();
	string $lstArrtA[] = `listAttr -ud AnimAssistant`;
	int $iPlayblastPt = stringArrayFind( "PlayblastPt", 0, $lstArrtA );
	if ($iPlayblastPt==-1){
		addAttr -dt "string" -longName "PlayblastPt" AnimAssistant;
	}
	int $iPlayblastPost = stringArrayFind( "PlayblastPost", 0, $lstArrtA );
	if ($iPlayblastPost==-1){
		addAttr -dt "string" -longName "PlayblastPost" AnimAssistant;
	}
	int $iPlayblastPre = stringArrayFind( "PlayblastPre", 0, $lstArrtA );
	if ($iPlayblastPre==-1){
		addAttr -dt "string" -longName "PlayblastPre" AnimAssistant;
	}
	setAttr -type "string" AnimAssistant.PlayblastPre ($preField);
}

global proc PostEdPB(){
	global string $pbPostfix;
	string $postField = `textField -q -tx $pbPostfix`;
	CreateIfNotExistNodeAttribute();
	string $lstArrtA[] = `listAttr -ud AnimAssistant`;
	int $iPlayblastPt = stringArrayFind( "PlayblastPt", 0, $lstArrtA );
	if ($iPlayblastPt==-1){
		addAttr -dt "string" -longName "PlayblastPt" AnimAssistant;
	}
	int $iPlayblastPost = stringArrayFind( "PlayblastPost", 0, $lstArrtA );
	if ($iPlayblastPost==-1){
		addAttr -dt "string" -longName "PlayblastPost" AnimAssistant;
	}
	int $iPlayblastPre = stringArrayFind( "PlayblastPre", 0, $lstArrtA );
	if ($iPlayblastPre==-1){
		addAttr -dt "string" -longName "PlayblastPre" AnimAssistant;
	}
	setAttr -type "string" AnimAssistant.PlayblastPost ($postField);
}

global proc PastePrePBSt(){
	global string $framest;
	global string $frameen;
	global string $pbPrefix;
	string $getStFr = `textField -q -tx $framest`;
	string $getEnFr = `textField -q -tx $frameen`;
	string $getPreF = `textField -q -tx $pbPrefix`;

	string $lstArrtA[] = `listAttr -ud AnimAssistant`;

	int $iPlayblastPre = stringArrayFind( "PlayblastPre", 0, $lstArrtA );
	if ($iPlayblastPre==-1){
		addAttr -dt "string" -longName "PlayblastPre" AnimAssistant;
	}
	if($getEnFr != "" && $getStFr != ""){
		textField -e -tx ($getStFr+"_"+$getEnFr+"_"+$getPreF) $pbPrefix;
	}
	setAttr -type "string" AnimAssistant.PlayblastPre ($getStFr+"_"+$getEnFr+"_"+$getPreF);
}

global proc PastePrePBEn(){
	global string $framest;
	global string $frameen;
	global string $pbPrefix;
	string $getStFr = `textField -q -tx $framest`;
	string $getEnFr = `textField -q -tx $frameen`;
	string $getPreF = `textField -q -tx $pbPrefix`;

	string $lstArrtA[] = `listAttr -ud AnimAssistant`;

	int $iPlayblastPre = stringArrayFind( "PlayblastPre", 0, $lstArrtA );
	if ($iPlayblastPre==-1){
		addAttr -dt "string" -longName "PlayblastPre" AnimAssistant;
	}
	if($getEnFr != "" && $getStFr != ""){
		textField -e -tx ($getPreF+"_"+$getStFr+"_"+$getEnFr) $pbPrefix;
	}
	setAttr -type "string" AnimAssistant.PlayblastPre ($getPreF+"_"+$getStFr+"_"+$getEnFr);
}

global proc PastePostPBSt(){
	global string $framest;
	global string $frameen;
	global string $pbPostfix;
	string $getStFr = `textField -q -tx $framest`;
	string $getEnFr = `textField -q -tx $frameen`;
	string $getPpostF = `textField -q -tx $pbPostfix`;

	string $lstArrtA[] = `listAttr -ud AnimAssistant`;

	int $iPlayblastPost = stringArrayFind( "PlayblastPost", 0, $lstArrtA );
	if ($iPlayblastPost==-1){
		addAttr -dt "string" -longName "PlayblastPost" AnimAssistant;
	}

	if($getEnFr != "" && $getStFr != ""){
		textField -e -tx ($getStFr+"_"+$getEnFr+"_"+$getPpostF) $pbPostfix;
	}

	setAttr -type "string" AnimAssistant.PlayblastPost ($getStFr+"_"+$getEnFr+"_"+$getPpostF);
}

global proc PastePostPBEn(){
	global string $framest;
	global string $frameen;
	global string $pbPostfix;
	string $getStFr = `textField -q -tx $framest`;
	string $getEnFr = `textField -q -tx $frameen`;
	string $getPpostF = `textField -q -tx $pbPostfix`;

	string $lstArrtA[] = `listAttr -ud AnimAssistant`;

	int $iPlayblastPost = stringArrayFind( "PlayblastPost", 0, $lstArrtA );
	if ($iPlayblastPost==-1){
		addAttr -dt "string" -longName "PlayblastPost" AnimAssistant;
	}

	if($getEnFr != "" && $getStFr != ""){
		textField -e -tx ($getPpostF+"_"+$getStFr+"_"+$getEnFr) $pbPostfix;
	}

	setAttr -type "string" AnimAssistant.PlayblastPost ($getPpostF+"_"+$getStFr+"_"+$getEnFr);
}

global proc string getFFmpegExe(){
	$ffmpegPathValue = `getenv "FFMPEG_PATH"`;
	if ($ffmpegPathValue != "") {
		$ffmpegPathValue = ($ffmpegPathValue + "/ffmpeg.exe");
		$fileExists = `filetest -x $ffmpegPathValue`;
		if (!$fileExists) {
			$ffmpegPathValue = ($ffmpegPathValue + "/ffmpeg");
			$fileExists = `filetest -x $ffmpegPathValue`;
			if (!$fileExists) {
				print("Not found ffmeg exe");
				return "";
			}
		}
		return $ffmpegPathValue;
	}
	return "";
}

global proc string PlayblastPBImpl(string $camera){
	global string $framest;
	global string $frameen;
	global string $animnm;
	global string $pbPath;
	global string $pbPostfix;
	global string $pbPrefix;
	string $getPath = `textField -q -tx $pbPath`;
	string $getPpostF = `textField -q -tx $pbPostfix`;
	string $getPreF = `textField -q -tx $pbPrefix`;

	string $getStFr = `textField -q -tx $framest`;
	string $getEnFr = `textField -q -tx $frameen`;
	string $getNmFr = `textField -q -tx $animnm`;
	string $fform = `optionVar -q playblastFormat`;
	float $percent = `optionVar -q playblastScale`;
	int $scale = $percent * 100;
	int $quality = `optionVar -q playblastQuality`;
	string $compress = `optionVar -q playblastCompression`;
	int $pad = `optionVar -q playblastPadding`;
	int $isViewer = `optionVar -q playblastViewerOn`;
	int $isShowOrnaments = `optionVar -q playblastShowOrnaments`;
	int $displaySizeSource = `optionVar -q playblastDisplaySizeSource`;
	int $width = 0;
	int $height = 0;
	if ($displaySizeSource == 3) {
		$width = `optionVar -q playblastWidth`;
		$height = `optionVar -q playblastHeight`;
	} else if ($displaySizeSource == 2) {
		$width = `getAttr "defaultResolution.width"`;
		$height = `getAttr "defaultResolution.height"`;
	}
	$ffmpegPathValue = `getenv "FFMPEG_PATH"`;
	if ($ffmpegPathValue != "") {
		//$fform = "avi";
		//$compress = "none";
		$isViewer = 0;
		if ($width % 2 != 0) {
			$width = $width + 1;
		}
		if ($height % 2 != 0) {
			$height = $height + 1;
		}
	}

	if ($getStFr!="" && $getEnFr!="" && $getNmFr!="" && $getPath!=""){
		string $name = "";
		if ($camera != "") {
			$getNmFr = $camera + "_" + $getNmFr;
		}
		if($getPreF!="" && $getPpostF==""){
			$name = ($getPath+"/"+$getPreF+"_"+$getNmFr);
		} else if ($getPreF=="" && $getPpostF!=""){
			$name = ($getPath+"/"+$getNmFr+"_"+$getPpostF);
		} else if ($getPreF!="" && $getPpostF!=""){
			$name = ($getPath+"/"+$getPreF+"_"+$getNmFr+"_"+$getPpostF);
		} else {
			$name = ($getPath+"/"+$getNmFr);
		}

		$cmd = "playblast -forceOverwrite -fmt "+$fform+" -p "+$scale+" -compression "+$compress+" -quality "+$quality+" -viewer "+$isViewer+" -showOrnaments "+$isShowOrnaments+" -fp "+$pad+" -st "+$getStFr+" -et "+$getEnFr+" -f "+$name+" -widthHeight "+$width+" "+$height;
		print($cmd+"\n");
		if ($displaySizeSource == 1) {
			playblast -forceOverwrite -fmt $fform -p $scale -compression $compress -quality $quality -viewer $isViewer -showOrnaments $isShowOrnaments -fp $pad -st $getStFr -et $getEnFr -f $name;
		} else {
			playblast -forceOverwrite -fmt $fform -p $scale -compression $compress -quality $quality -viewer $isViewer -showOrnaments $isShowOrnaments -fp $pad -st $getStFr -et $getEnFr -f $name -widthHeight $width $height;
		}
		
		if ($ffmpegPathValue != "") {
			$ffmpegPathValue = getFFmpegExe();
			$movieFileName = $name+".avi";
			$findResult = `filetest -r $movieFileName`;
			if (!$findResult) {
				$movieFileName = $name+".mov";
				$findResult = `filetest -r $movieFileName`;
				if (!$findResult) {
					print("FFmpeg input file not found");
					return "";
				}
			}
			$outputFileName = $name+".mp4";
			$commandToRun = ($ffmpegPathValue+" -y -i \""+$movieFileName+"\" -vcodec h264 \""+$outputFileName + "\"");
			print($commandToRun+"\n");
			print(system($commandToRun));
			print("----------End of ffmpeg-----------\n");
			if (`filetest -r $outputFileName`) {
				sysFile -delete $movieFileName;
			}
			else {
				return "";
			}
			return $outputFileName;
		}
	}
	return "";
}

global proc int PlayblastPBAnim(string $anim, string $view, string $gMainProgressBar){
	global string $camerasList;
	string $orthoCameras[] = `textScrollList -q -si $camerasList`;
	string $outFiles[];
	for ($camera in $orthoCameras) {
		lookThru $camera $view;
		$fileName = PlayblastPBImpl($camera);
		if(`progressBar -q -ic $gMainProgressBar`)
		{
			print ("Playblast canceled after " + $anim);
			return 0;
		}
		$outFiles[size($outFiles)] = $fileName;
	}
	if (size($orthoCameras) == 0) {
		PlayblastPBImpl("");
	}
	
	$ffmpegPathValue = getFFmpegExe();
	if (size($outFiles) > 1 && $ffmpegPathValue != "") {
		global string $pbPath;
		string $getPath = `textField -q -tx $pbPath`;
		global string $animnm;
		string $getNmFr = `textField -q -tx $animnm`;
		$outputFileName = $getPath + "/" + $getNmFr + ".mp4";
		$commandToRun = ($ffmpegPathValue+" -y ");
		for ($file in $outFiles) {
			$commandToRun = ($commandToRun + "-i \"" + $file + "\" ");
		}
		$commandToRun = ($commandToRun + "-filter_complex hstack \"" + $outputFileName + "\"");
		print("Try to merge cameras video");
		print($commandToRun + "\n");
		print(system($commandToRun));
	}

	return 1;
}

global proc PlayblastPB(){
	string $defaultCamera = `lookThru -q`;
	string $view = `getPanel -withFocus`;
	global string $gMainProgressBar;
	int $maxPBar = 10000;
	progressBar -e -bp -ii 1 -imp 1 -max $maxPBar $gMainProgressBar;
	
	global string $animli;
	string $objsfke[] = `textScrollList -q -si $animli`;
	for ($anim in $objsfke){
		SetAnimationClip($anim);
		if (PlayblastPBAnim($anim, $view, $gMainProgressBar) == 0) {
			break;
		}
		progressBar -e -s 1 $gMainProgressBar;
	}
	
	progressBar -e -endProgress $gMainProgressBar;
	lookThru $defaultCamera $view;
}

global proc AnimSel () {
	string $slobjec[] = `ls -sl`;
	global string $objectli;
	textScrollList -e -ra $objectli;
	for ($ob in $slobjec){
		textScrollList -e -a $ob $objectli;
	}
}

global proc doWrite (int $spacer) {
	global string $spa;
	if ($spacer == 1){
		$spa = "-objectSpace";
	} else {
		$spa = "-worldSpace";
	}
}

global proc AnimAssistMain () {
	global string $spa;
	string $slobje[] = `ls -sl`;
	group -empty -n ("one_f_tmp_grp");
	for ($z in $slobje){
		group -empty -n ($z+"_tmp_grp");
		parent ($z+"_tmp_grp") "one_f_tmp_grp";
	}
	float $sttr = `playbackOptions -q -min`;
	float $endtr = `playbackOptions -q -max`;
	float $i;
	for ( $i=$sttr; $i<=$endtr; ++$i ){
		float $crtm = `currentTime $i`;
		for ($k in $slobje){
			if(`keyframe -time $crtm -query -keyframeCount $k` != 0){
				float $positeo[] = `xform $spa -query -translation $k`;
				float $rotatio[] = `xform $spa -query -ro $k`;
				move -a $spa $positeo[0] $positeo[1] $positeo[2] ($k+"_tmp_grp");
				rotate -a $spa $rotatio[0] $rotatio[1] $rotatio[2] ($k+"_tmp_grp");
				setKeyframe -breakdown 0 ($k+"_tmp_grp");
			}
		}
	}
}

global proc moveItUP () {
	global string $objectli;
	string $objsall[] = `textScrollList -q -selectItem $objectli`;
	int $objssil[] = `textScrollList -q -selectIndexedItem $objectli`;
	for ($op=0;$op< `size $objssil`; ++$op){
		int $prevPos = ( $objssil[$op] == 1 )?$objssil[$op]:($objssil[$op] - 1);
		textScrollList -e -removeIndexedItem $objssil[$op] $objectli;
		textScrollList -e -appendPosition $prevPos $objsall[$op] $objectli;
		textScrollList -e -selectItem $objsall[$op] $objectli;
	}
}

global proc moveItDN () {
	global string $objectli;
	string $objsall[] = `textScrollList -q -selectItem $objectli`;
	int $objssil[] = `textScrollList -q -selectIndexedItem $objectli`;
	int $objsnam = `textScrollList -q -numberOfItems $objectli`;
	for ( $op = (`size $objssil` - 1); $op >= 0; --$op ) {
		int $nextPos = ( $objssil[$op] == $objsnam )?$objssil[$op]:($objssil[$op] + 1);
		textScrollList -e -removeIndexedItem $objssil[$op] $objectli;
		textScrollList -e -appendPosition $nextPos $objsall[$op] $objectli;
		textScrollList -e -selectItem $objsall[$op] $objectli;
	}
}



global proc RecIT () {
	global string $spa;
	global string $animrad;
	global string $objectli;
	string $sell[] = `ls -sl`;
	float $intag[];
	float $outtag[];
	int $loctag[];
	string $chanls[] = { ".translateX", ".translateY", ".translateZ", ".rotateX", ".rotateY", ".rotateZ" };
	string $slobje[] = `textScrollList -q -ai $objectli`;
	int $grex = `objExists "one_f_tmp_grp"`;
	if ($grex == 0){
		group -empty -n ("one_f_tmp_grp");
	}
	for ($z in $slobje){
		int $grexobj = `objExists ("|one_f_tmp_grp|" + $z+"_tmp_grp")`;
		if ($grexobj == 0){
			group -empty -n ($z+"_tmp_grp");
			int $ror = `getAttr ($z + ".rotateOrder")`;
			parent ("|" + $z+"_tmp_grp") "one_f_tmp_grp";
			setAttr ("|one_f_tmp_grp|" + $z+"_tmp_grp"+".rotateOrder") $ror;
		} else {
			delete ("|one_f_tmp_grp|" + $z+"_tmp_grp");
			group -empty -n ($z+"_tmp_grp");
			parent ("|" + $z+"_tmp_grp") "one_f_tmp_grp";
		}
	}
	string $k;

	float $fsfr;
	float $lsfr;
	float $sttr = `playbackOptions -q -min`;
	float $endtr = `playbackOptions -q -max`;

 	if (`keyframe  -t $sttr -q -kc $slobje`) {
		$fsfr = $sttr;
 	} else {
		$fsfr = `findKeyframe -time $sttr -which next $slobje`;
 	}
 	if (`keyframe  -t $endtr -q -kc $slobje`) {
		$lsfr = $endtr;
 	} else {
		$lsfr = `findKeyframe -time $endtr -which previous $slobje`;
	}
	currentTime -edit $fsfr;


	while ( `currentTime -q` != $lsfr) {
		float $crtm = `currentTime -q`;
		for ($k in $slobje){
			if(`keyframe -time $crtm -query -keyframeCount $k` != 0){
				if ($spa == "-objectSpace"){
					float $rota[] = `getAttr ($k + ".rotate")`;
					float $tra[] = `getAttr ($k + ".translate")`;
					setAttr ("|one_f_tmp_grp|" + $k+"_tmp_grp.translate") $tra[0] $tra[1] $tra[2];
					setAttr ("|one_f_tmp_grp|" + $k+"_tmp_grp.rotate") $rota[0] $rota[1] $rota[2];
					setKeyframe -breakdown 0 ("|one_f_tmp_grp|" + $k+"_tmp_grp");
				} else {
					float $positeo[] = `xform $spa -query -translation $k`;
					float $rotatio[] = `xform $spa -query -ro $k`;
					move -a $spa $positeo[0] $positeo[1] $positeo[2] ("|one_f_tmp_grp|" + $k+"_tmp_grp");
					rotate -a $spa $rotatio[0] $rotatio[1] $rotatio[2] ("|one_f_tmp_grp|" + $k+"_tmp_grp");
					setKeyframe -breakdown 0 ("|one_f_tmp_grp|" + $k+"_tmp_grp");
				}
				for ($zit=0;$zit<6;++$zit){
					int $obex = `objExists ($k + $chanls[$zit])`;
					if ($obex == 1){
						int $ktest = `keyframe  -t $crtm -q -kc ($k + $chanls[$zit])` ;
						if ($ktest == 1){
							$intag = `keyTangent -t $crtm -q -inAngle ($k + $chanls[$zit])` ;
							$outtag = `keyTangent -t $crtm -q -outAngle ($k + $chanls[$zit])` ;
							$loctag = `keyTangent -t $crtm -q -lock ($k + $chanls[$zit])` ;

							keyTangent -e -t $crtm -lock $loctag[0] ("|one_f_tmp_grp|" + $k +"_tmp_grp" + $chanls[$zit]);
							keyTangent -e -t $crtm -inAngle $intag[0]("|one_f_tmp_grp|" + $k +"_tmp_grp" + $chanls[$zit]);
							keyTangent -e -t $crtm -outAngle $outtag[0] ("|one_f_tmp_grp|" + $k +"_tmp_grp" + $chanls[$zit]);
						}
					}
				}
			}
		}
		currentTime -edit `findKeyframe  -which next $slobje`;
	}

	for ($k in $slobje){
		if(`keyframe -time $lsfr -query -keyframeCount $k` != 0){

			if ($spa == "-objectSpace"){
				float $rota[] = `getAttr ($k + ".rotate")`;
				float $tra[] = `getAttr ($k + ".translate")`;
				setAttr ("|one_f_tmp_grp|" + $k+"_tmp_grp.translate") $tra[0] $tra[1] $tra[2];
				setAttr ("|one_f_tmp_grp|" + $k+"_tmp_grp.rotate") $rota[0] $rota[1] $rota[2];
				setKeyframe -breakdown 0 ("|one_f_tmp_grp|" + $k+"_tmp_grp");
			} else {
				float $positeo[] = `xform $spa -query -translation $k`;
				float $rotatio[] = `xform $spa -query -ro $k`;
				move -a $spa $positeo[0] $positeo[1] $positeo[2] ("|one_f_tmp_grp|" + $k+"_tmp_grp");
				rotate -a $spa $rotatio[0] $rotatio[1] $rotatio[2] ("|one_f_tmp_grp|" + $k+"_tmp_grp");
				setKeyframe -breakdown 0 ("|one_f_tmp_grp|" + $k+"_tmp_grp");
			}

			for ($zit=0;$zit<6;++$zit){
				int $obex = `objExists ($k + $chanls[$zit])`;
				if ($obex == 1){
					int $ktest = `keyframe  -t $lsfr -q -kc ($k + $chanls[$zit])` ;
					if ($ktest == 1){
						$intag = `keyTangent -t $lsfr -q -inAngle ($k + $chanls[$zit])` ;
						$outtag = `keyTangent -t $lsfr -q -outAngle ($k + $chanls[$zit])` ;
						$loctag = `keyTangent -t $lsfr -q -lock ($k + $chanls[$zit])` ;

						keyTangent -e -t $lsfr -lock $loctag[0] ("|one_f_tmp_grp|" + $k +"_tmp_grp" + $chanls[$zit]);
						keyTangent -e -t $lsfr -inAngle $intag[0]("|one_f_tmp_grp|" + $k +"_tmp_grp" + $chanls[$zit]);
						keyTangent -e -t $lsfr -outAngle $outtag[0] ("|one_f_tmp_grp|" + $k +"_tmp_grp" + $chanls[$zit]);
					}
				}
			}
		}
	}
	string $clid[] = `listRelatives -c one_f_tmp_grp`;
	performEulerFilter graphEditor1FromOutliner;
	filterCurve $clid.rotateZ $clid.rotateY $clid.rotateX;
	select -r $sell;
}



global proc BakeKeys (){
	global string $spa;
	global string $animrad;
	global string $objectli;
	string $chanls[] = { ".translateX", ".translateY", ".translateZ", ".rotateX", ".rotateY", ".rotateZ" };
	int $nuse = `textScrollList -q -nsi $objectli`;
	int $nasel =`textScrollList -q -ni $objectli`;
	string $objsfk[];
	if ($nuse == $nasel || $nuse == 0){
		$objsfk = `textScrollList -q -ai $objectli`;
	} else {
		$objsfk = `textScrollList -q -si $objectli`;
	}
	string $les[] = `ls -sl`;

	string $clid[] = `listRelatives -c one_f_tmp_grp`;
	float $fsfr;
	float $lsfr;
	float $sttr = `playbackOptions -q -min`;
	float $endtr = `playbackOptions -q -max`;

	if (`keyframe  -t $sttr -q -kc $clid`) {
		$fsfr = $sttr;
	} else {
		$fsfr = `findKeyframe -time $sttr -which next $clid`;
	}
	if (`keyframe  -t $endtr -q -kc $clid`) {
		$lsfr = $endtr;
	} else {
		$lsfr = `findKeyframe -time $endtr -which previous $clid`;
	}
	currentTime -edit $fsfr;

	while (  `currentTime -q` != $lsfr) {
		float $crtim = `currentTime -q`;

		for ($m in $objsfk){
			string $actobj = "|one_f_tmp_grp|" + $m + "_tmp_grp";
			if(`keyframe -time $crtim -query -keyframeCount $actobj` != 0){

				if ($spa == "-objectSpace"){
					float $rota[] = `getAttr ($actobj + ".rotate")`;
					float $tra[] = `getAttr ($actobj + ".translate")`;
					if (`getAttr -l ($m + ".translateX")`==0){
						setAttr ($m + ".translateX") $tra[0];
					}
					if (`getAttr -l ($m + ".translateY")`==0){
						setAttr ($m + ".translateY") $tra[1];
					}
					if (`getAttr -l ($m + ".translateZ")`==0){
						setAttr ($m + ".translateZ") $tra[2];
					}
					if (`getAttr -l ($m + ".rotateX")`==0){
						setAttr ($m + ".rotateX") $rota[0];
					}
					if (`getAttr -l ($m + ".rotateY")`==0){
						setAttr ($m + ".rotateY") $rota[1];
					}
					if (`getAttr -l ($m + ".rotateZ")`==0){
						setAttr ($m + ".rotateZ") $rota[2];
					}
					setKeyframe -breakdown 0 $m ;
				} else {
					float $positeo[] = `xform $spa -query -translation $actobj`;
					float $rotatio[] = `xform $spa -query -ro $actobj`;
					move -a $spa $positeo[0] $positeo[1] $positeo[2] $m ;
					rotate -a $spa $rotatio[0] $rotatio[1] $rotatio[2] $m ;
					setKeyframe -breakdown 0 $m ;
				}

				for ($zit=0;$zit<6;++$zit){
					int $obex = `objExists ($m + $chanls[$zit])`;
					if ($obex == 1){
						int $ktest = `keyframe  -t $crtim -q -kc ($m + $chanls[$zit])` ;
						if ($ktest == 1){
							$intag = `keyTangent -t $crtim -q -inAngle ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;
							$outtag = `keyTangent -t $crtim -q -outAngle ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;
							$loctag = `keyTangent -t $crtim -q -lock ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;

							keyTangent -e -t $crtim -lock $loctag[0] ($m + $chanls[$zit]);
							keyTangent -e -t $crtim -inAngle $intag[0]($m + $chanls[$zit]);
							keyTangent -e -t $crtim -outAngle $outtag[0] ($m + $chanls[$zit]);
						}
					}
				}
			}
		}
		currentTime -e `findKeyframe -which next $clid`;
	}

	for ($m in $objsfk){
		string $actobj = "|one_f_tmp_grp|" + $m + "_tmp_grp";
		if(`keyframe -time $lsfr -query -keyframeCount $actobj` != 0){
			if ($spa == "-objectSpace"){
				float $rota[] = `getAttr ($actobj + ".rotate")`;

				float $tra[] = `getAttr ($actobj + ".translate")`;
				if (`getAttr -l ($m + ".translateX")`==0){
					setAttr ($m + ".translateX") $tra[0];
				}
				if (`getAttr -l ($m + ".translateY")`==0){
					setAttr ($m + ".translateY") $tra[1];
				}
				if (`getAttr -l ($m + ".translateZ")`==0){
					setAttr ($m + ".translateZ") $tra[2];
				}
				if (`getAttr -l ($m + ".rotateX")`==0){
					setAttr ($m + ".rotateX") $rota[0];
				}
				if (`getAttr -l ($m + ".rotateY")`==0){
					setAttr ($m + ".rotateY") $rota[1];
				}
				if (`getAttr -l ($m + ".rotateZ")`==0){
					setAttr ($m + ".rotateZ") $rota[2];
				}
				setKeyframe -breakdown 0 $m ;
			} else {
				float $positeo[] = `xform $spa -query -translation $actobj`;
				float $rotatio[] = `xform $spa -query -ro $actobj`;
				move -a $spa $positeo[0] $positeo[1] $positeo[2] $m ;
				rotate -a $spa $rotatio[0] $rotatio[1] $rotatio[2] $m ;
				setKeyframe -breakdown 0 $m ;
			}
			for ($zit=0;$zit<6;++$zit){
				int $obex = `objExists ($m + $chanls[$zit])`;
				if ($obex == 1){
					int $ktest = `keyframe  -t $lsfr -q -kc ($m + $chanls[$zit])` ;
					if ($ktest == 1){
						$intag = `keyTangent -t $lsfr -q -inAngle ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;
						$outtag = `keyTangent -t $lsfr -q -outAngle ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;
						$loctag = `keyTangent -t $lsfr -q -lock ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;

						keyTangent -e -t $lsfr -lock $loctag[0] ($m + $chanls[$zit]);
						keyTangent -e -t $lsfr -inAngle $intag[0]($m + $chanls[$zit]);
						keyTangent -e -t $lsfr -outAngle $outtag[0] ($m + $chanls[$zit]);
					}
				}
			}
		}
	}
	select -r $les;
}

global proc BakeAllKeys (){
	global string $spa;
	global string $animrad;
	global string $objectli;
	string $les[] = `ls -sl`;
	string $chanls[] = { ".translateX", ".translateY", ".translateZ", ".rotateX", ".rotateY", ".rotateZ" };
	int $nuse = `textScrollList -q -nsi $objectli`;
	int $nasel =`textScrollList -q -ni $objectli`;
	string $objsfk[];
	$objsfk = `textScrollList -q -ai $objectli`;

	string $clid[] = `listRelatives -c one_f_tmp_grp`;
	float $fsfr;
	float $lsfr;
	float $sttr = `playbackOptions -q -min`;
	float $endtr = `playbackOptions -q -max`;

	if (`keyframe  -t $sttr -q -kc $clid`) {
		$fsfr = $sttr;
	} else {
		$fsfr = `findKeyframe -time $sttr -which next $clid`;
	}
	if (`keyframe  -t $endtr -q -kc $clid`) {
		$lsfr = $endtr;
	} else {
		$lsfr = `findKeyframe -time $endtr -which previous $clid`;
	}
	currentTime -edit $fsfr;

	while (  `currentTime -q` != $lsfr) {
		float $crtim = `currentTime -q`;

		for ($m in $objsfk){
			string $actobj = "|one_f_tmp_grp|" + $m + "_tmp_grp";
			if(`keyframe -time $crtim -query -keyframeCount $actobj` != 0){
				float $positeo[] = `xform $spa -query -translation $actobj`;
				float $rotatio[] = `xform $spa -query -ro $actobj`;
				//string $objnm = `substitute "_tmp_grp" $m ""`;
				move -a $spa $positeo[0] $positeo[1] $positeo[2] $m ;
				rotate -a $spa $rotatio[0] $rotatio[1] $rotatio[2] $m ;
				setKeyframe -breakdown 0 $m ;

				for ($zit=0;$zit<6;++$zit){
					int $obex = `objExists ($m + $chanls[$zit])`;
					if ($obex == 1){
						int $ktest = `keyframe  -t $crtim -q -kc ($m + $chanls[$zit])` ;
						if ($ktest == 1){
							$intag = `keyTangent -t $crtim -q -inAngle ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;
							$outtag = `keyTangent -t $crtim -q -outAngle ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;
							$loctag = `keyTangent -t $crtim -q -lock ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;

							keyTangent -e -t $crtim -lock $loctag[0] ($m + $chanls[$zit]);
							keyTangent -e -t $crtim -inAngle $intag[0]($m + $chanls[$zit]);
							keyTangent -e -t $crtim -outAngle $outtag[0] ($m + $chanls[$zit]);
						}
					}
				}
			}
		}
		currentTime -e `findKeyframe -which next $clid`;
	}

	for ($m in $objsfk){
		string $actobj = "|one_f_tmp_grp|" + $m + "_tmp_grp";
		if(`keyframe -time $lsfr -query -keyframeCount $actobj` != 0){
			float $positeo[] = `xform $spa -query -translation $actobj`;
			float $rotatio[] = `xform $spa -query -ro $actobj`;
			//string $objnm = `substitute "_tmp_grp" $m ""`;
			move -a $spa $positeo[0] $positeo[1] $positeo[2] $m ;
			rotate -a $spa $rotatio[0] $rotatio[1] $rotatio[2] $m ;
			setKeyframe -breakdown 0 $m ;

			for ($zit=0;$zit<6;++$zit){
				int $obex = `objExists ($m + $chanls[$zit])`;
				if ($obex == 1){
					int $ktest = `keyframe  -t $lsfr -q -kc ($m + $chanls[$zit])` ;
					if ($ktest == 1){
						$intag = `keyTangent -t $lsfr -q -inAngle ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;
						$outtag = `keyTangent -t $lsfr -q -outAngle ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;
						$loctag = `keyTangent -t $lsfr -q -lock ("|one_f_tmp_grp|" + $m +"_tmp_grp" + $chanls[$zit])` ;

						keyTangent -e -t $lsfr -lock $loctag[0] ($m + $chanls[$zit]);
						keyTangent -e -t $lsfr -inAngle $intag[0]($m + $chanls[$zit]);
						keyTangent -e -t $lsfr -outAngle $outtag[0] ($m + $chanls[$zit]);
					}
				}
			}
		}
	}

	select -r $les;

}

global proc DeleteSys () {
	delete "one_f_tmp_grp";
}

global proc RenAmme () {
	global string $objectli;
	global string $objecttx;
	string $lss[] = `ls -sl`;
	string $nmsp = `match "^.*:" $lss[0]`;
	string $nmo[] = `ls -r 1 ("*" + $lss[0] + "*")`;
	string $nmse[] = `select -r $nmo[0]`;
	string $nmsp_name = `match "[^:]*$" $lss[0]`;
	string $grm[] = `listRelatives -c "one_f_tmp_grp"`;
	string $s;
	string $dr;

	for ($s in $grm){
		string $component = `match "[^:]*$" $s`;

		string $tmprem = `substitute "_tmp_grp" $component ""`;
		string $nmsptemp = `match "^.*:" $s`;
		if  ( $tmprem == $nmsp_name){
			for ($r in $grm){
				string $componentname = `match "[^:]*$" $r`;
				rename ("|one_f_tmp_grp|" + $r) ($nmsp + $componentname);
			}
		}
	}
	string $gram[] = `listRelatives -c "one_f_tmp_grp"`;
	textScrollList -e -ra $objectli;
	for ($obg in $gram){
		string $tamprem = `substitute "_tmp_grp" $obg ""`;
		textScrollList -e -a $tamprem $objectli;
	}

}


global proc DeleteAinm () {
	global string $objectli;
	string $objsall[] = `textScrollList -q -selectItem $objectli`;
	string $objsallinl[] = `textScrollList -q -ai $objectli`;
	string $objdiff[] = stringArrayRemoveExact($objsall, $objsallinl);
	int $grex = `objExists "one_f_tmp_grp"`;
	textScrollList -e -ra $objectli;
	if ($grex == 1 ){
		for ($ad in $objsall){
			delete ($ad + "_tmp_grp");
		}
	}
	for ($ob in $objdiff){
		textScrollList -e -a $ob $objectli;
	}
}


global proc SetDynRootKey () {
	float $pointpos[] = `xform -q -ws -t "Dinamic_pointer"`;
	float $pointrot[] = `xform -q -ws -ro "Dinamic_pointer"`;
	float $contpos[] = `xform -q -ws -t "Dinamic_cont"`;
	float $controt[] = `xform -q -ws -ro "Dinamic_cont"`;
	float $tm = `currentTime -query`;
	currentTime $tm;
	setKeyframe "Dinamic_root";
	setKeyframe "Dinamic_cont";
	currentTime ($tm+1);
	move -ws $pointpos[0] $pointpos[1] $pointpos[2] "Dinamic_root";
	rotate -ws $pointrot[0] $pointrot[1] $pointrot[2] "Dinamic_root";
	move -ws $pointpos[0] $pointpos[1] $pointpos[2] "Dinamic_pointer";
	rotate -ws $pointrot[0] $pointrot[1] $pointrot[2] "Dinamic_pointer";
	move -ws $contpos[0] $contpos[1] $contpos[2] "Dinamic_cont";
	rotate -ws $controt[0] $controt[1] $controt[2] "Dinamic_cont";
	setKeyframe "Dinamic_root";
	setKeyframe "Dinamic_cont";
	select -r "Dinamic_root";
}

global proc CreateDynRoot () {
	string $rots[] = `ls -sl`;
	if ($rots[0]!=""){
		float $boundingBox[] = `xform -q -bb $rots[0]`;
		$xSize = $boundingBox[3]-$boundingBox[0];
		circle -ch on -o on -nr 0 1 0 -c 0 0 0 -r ($xSize/2+4) -n "Dinamic_root";
		circle -ch on -o on -nr 0 1 0 -c 0 0 0 -r ($xSize/2+2) -n "Dinamic_cont";
		setAttr "Dinamic_contShape.visibility" 1;
		nurbsSquare -ch on -o on -nr 0 1 0 -sl1 ($xSize/2+ 7) -sl2 ($xSize/2 + 7) -c 0 0 0  -n "Dinamic_pointer_tmp";
		{
			string $sqobj[] = `listRelatives -c "Dinamic_pointer_tmp"`;
			$target = $sqobj[size($sqobj)-1];
			for ($p=0; $p<(size($sqobj)-1);++$p){
				parent $sqobj[$p] $target;
				makeIdentity -apply true -t 1 -r 1 -s 1 -n 0;
				$shp = `listRelatives -shapes`;
				select $shp;
				select -add $target;
				parent -s -r;
			}
		}
		select -r "Dinamic_pointer_tmp";
		ungroup;
		rename "Dinamic_pointer";
		{
			string $sqobj[] = `listRelatives -c -typ "transform"  "Dinamic_pointer"`;
			select $sqobj;
			delete;
		}
		parent "Dinamic_pointer" "Dinamic_root";
		float $objpos[] = `xform -q -ws -t $rots[0]`;
		float $objrot[] = `xform -q -ws -ro $rots[0]`;
		parent "Dinamic_cont" "Dinamic_root";
		move -ws $objpos[0] $objpos[1] $objpos[2] "Dinamic_root";
		rotate -ws $objrot[0] $objrot[1] $objrot[2] "Dinamic_root";
		parent $rots[0] "Dinamic_cont";
		setAttr "Dinamic_rootShape.overrideEnabled" 1;
		setAttr "Dinamic_rootShape.overrideRGBColors" 1;
		setAttr "Dinamic_rootShape.overrideColorRGB" 0.02 0.372359 1;
		setAttr "Dinamic_contShape.overrideEnabled" 1;
		setAttr "Dinamic_contShape.overrideRGBColors" 1;
		setAttr "Dinamic_contShape.overrideColorRGB" 0 0 0;
		setAttr "topDinamic_pointer_tmpShape.overrideEnabled" 1;
		setAttr "topDinamic_pointer_tmpShape.overrideRGBColors" 1;
		setAttr "topDinamic_pointer_tmpShape.overrideColorRGB" 0.737864 0.0951845 0.311821;
		setAttr "Dinamic_pointerShape.overrideEnabled" 1;
		setAttr "Dinamic_pointerShape.overrideRGBColors" 1;
		setAttr "Dinamic_pointerShape.overrideColorRGB" 0.737864 0.0951845 0.311821;
		setAttr "leftDinamic_pointer_tmpShape.overrideEnabled" 1;
		setAttr "leftDinamic_pointer_tmpShape.overrideRGBColors" 1;
		setAttr "leftDinamic_pointer_tmpShape.overrideColorRGB" 0.737864 0.0951845 0.311821;
		setAttr "bottomDinamic_pointer_tmpShape.overrideEnabled" 1;
		setAttr "bottomDinamic_pointer_tmpShape.overrideRGBColors" 1;
		setAttr "bottomDinamic_pointer_tmpShape.overrideColorRGB" 0.737864 0.0951845 0.311821;
	}
}

global proc DeleteDynRoot () {
	select "Dinamic_cont";
	string $lsch[] = `listRelatives -c -f`;
	if ($lsch[0]!=""){
		parent -world $lsch[1];
	}
	delete "Dinamic_root";

}

global proc ShapCont () {
	string $rotso[] = `ls -sl`;
	float $objposa[] = `xform -q -ws -t $rotso[0]`;
	float $objrosa[] = `xform -q -ws -ro $rotso[0]`;
	move -ws $objposa[0] $objposa[1] $objposa[2] "Dinamic_pointer";
	rotate -ws $objrosa[0] $objrosa[1] $objrosa[2] "Dinamic_pointer";
}

global proc RotPosContX () {
	float $objrosapX[] = `xform -q -os -ro Dinamic_pointer`;
	rotate -os ($objrosapX[0] + 90) $objrosapX[1] $objrosapX[2] "Dinamic_pointer";
}

global proc RotNegContX () {
	float $objrosanX[] = `xform -q -os -ro Dinamic_pointer`;
	rotate -os ($objrosanX[0] - 90) $objrosanX[1] $objrosanX[2] "Dinamic_pointer";
}

global proc RotPosContY () {
	float $objrosapY[] = `xform -q -os -ro Dinamic_pointer`;
	rotate -os $objrosapY[0] ($objrosapY[1] + 90) $objrosapY[2] "Dinamic_pointer";
}

global proc RotNegContY () {
	float $objrosanY[] = `xform -q -os -ro Dinamic_pointer`;
	rotate -os $objrosanY[0] ($objrosanY[1] - 90) $objrosanY[2] "Dinamic_pointer";
}

global proc RotPosContZ () {
	float $objrosapZ[] = `xform -q -os -ro Dinamic_pointer`;
	rotate -os $objrosapZ[0] $objrosapZ[1] ($objrosapZ[2] + 90) "Dinamic_pointer";
}

global proc RotNegContZ () {
	float $objrosanZ[] = `xform -q -os -ro Dinamic_pointer`;
	rotate -os $objrosanZ[0] $objrosanZ[1] ($objrosanZ[2] + 90) "Dinamic_pointer";
}

global proc AppendAnimName () {
	global string $framest;
	global string $frameen;
	global string $animli;
	global string $animnm;
	global string $animfl;
	string $qannm = `textField -q -tx $animnm`;
	string $fannm = `textField -q -tx $animfl`;
	string $ststfr = `textField -q -tx $framest` ;
	string $stenfr = `textField -q -tx $frameen` ;
	int $objsfik[] = `textScrollList -q -sii $animli`;
	if ($qannm != "" && $ststfr != "" && $stenfr != ""){
		int $frst = `textField -q -tx $framest`;
		int $fren = `textField -q -tx $frameen`;
		CreateIfNotExistNodeAttribute();

		string $objsfak[] = `textScrollList -q -si $animli`;

		$textFieldValue = `textField -q -tx $animnm`;

		//change attribute start
		string $sellle = `textField -q -tx $animnm`;
		while ( $sellle != ( $sellle = `substitute " " $sellle "_"` ) );
		string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($animlinm, " ");
		int $indexarr = stringArrayFind( $objsfak[0], 0, $animlinmarr );
		for ($tip = 0; $tip < size ($animlinmarr);++$tip){
			string $splitedResult[] = stringToStringArray($animlinmarr[$tip], "|");
			if (size($splitedResult) > 1)
				$animlinmarr[$tip] = $splitedResult[1];
		}

		stringArrayInsertAtIndex(($indexarr+1) , $animlinmarr, ($sellle + "_" + $frst + "-" + $fren));
		string $finpada;
		for ($tp = 0; $tp < size ($animlinmarr);++$tp){
			string $padString = "0";
			string $prt = (string)($tp+1);
			if((size ($prt))<2)
				for($i=0;$i<(2-(size ($prt)));$i++){
					$padString=$padString+"0" ;
				}
			$finpada = $padString+($tp +1);
			$animlinmarr[$tp] = $finpada + "|" + $animlinmarr[$tp];
		}
		AppendUndo();
		setAttr -type "string" AnimAssistant.AnimationClipName (stringArrayToString($animlinmarr, " "));
		//change attribute end

		//change attribute StFrame start
		string $animlist = `getAttr AnimAssistant.StartFrame`;
		string $animlistarr[] = stringToStringArray($animlist, " ");
		stringArrayInsertAtIndex(($indexarr+1), $animlistarr, $frst);
		setAttr -type "string" AnimAssistant.StartFrame (stringArrayToString($animlistarr, " "));
		//change attribute StFrame end
		//change attribute EnFrame start
		string $animlien = `getAttr AnimAssistant.EndFrame`;
		string $animlienarr[] = stringToStringArray($animlien, " ");
		stringArrayInsertAtIndex(($indexarr+1), $animlienarr, $fren);
		setAttr -type "string" AnimAssistant.EndFrame (stringArrayToString($animlienarr, " "));
		//change attribute EnFrame end

		textScrollList -e -ra $animli;
		$animlinm = `getAttr AnimAssistant.AnimationClipName`;
		$animlinmarr = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
		textScrollList -e -sii ($objsfik[0]+1) $animli;
	} else {
	}
	if ($fannm != ""){
		textScrollList -e -ra $animli;
		string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
		string $filteredList[];
		string $aite[] = `textScrollList -q -ai $animli`;
		int $i = 0;
		for ($each in $aite){
			string $keyword_lower = `tolower $fannm`;
			string $each_lower = `tolower $each`;
			string $findMatch = `match $keyword_lower $each_lower `;
			if ($findMatch == $keyword_lower ){
				$filteredList[$i] = $each;
				$i++;
			}
		}
		textScrollList -edit -ra $animli;
		for ($each in $filteredList){
			textScrollList -edit -append $each $animli;
		}

	} else {
		textScrollList -e -ra $animli;
		$animlinm = `getAttr AnimAssistant.AnimationClipName`;
		$animlinmarr = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
		textScrollList -e -sii ($objsfik[0]+1) $animli;
	}
}


global proc  AnimFilter() {
	global string $framest;
	global string $frameen;
	global string $animli;
	global string $animfl;
	global string $animnm;
	string $newnmstring;
	string $qannm = `textField -q -tx $animfl`;
	string $slit[] = `textScrollList -q -si $animli`;
	if ($qannm != ""){
		textScrollList -e -ra $animli;
		string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
		string $filteredList[];
		string $aite[] = `textScrollList -q -ai $animli`;
		int $i = 0;
		for ($each in $aite){
			string $keyword_lower = `tolower $qannm`;
			string $each_lower = `tolower $each`;
			string $findMatch = `match $keyword_lower $each_lower `;
			if ($findMatch == $keyword_lower ){
				$filteredList[$i] = $each;
				$i++;
			}
		}
		textScrollList -edit -ra $animli;
		for ($each in $filteredList){
			textScrollList -edit -append $each $animli;
		}
	} else {
		textScrollList -e -ra $animli;
		$animlinm = `getAttr AnimAssistant.AnimationClipName`;
		$animlinmarr = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
	}
	string $slot[] = `textScrollList -q -ai $animli`;
	for ($si in $slit){

			int $indexarr = stringArrayFind( $si, 0, $slot);
			if ( $indexarr >= 0){
				textScrollList -e -si $si $animli;
			}
		}

}

global proc RefreshAnimList() {
	updateAnims();
}

global proc RemoveAnimName() {
	global string $framest;
	global string $frameen;
	global string $animli;
	global string $animnm;
	string $animlinmarr[];
	clear($animlinmarr);
	global string $animfl;
	string $newnmstring;
	string $qannm = `textField -q -tx $animfl`;
	string $aite[] = `textScrollList -q -ai $animli`;
	int $numseline[] = `textScrollList -q -sii $animli`;
	int $qseline = `textScrollList -q -nsi $animli`;
	string $seli[] = `textScrollList -q -si $animli`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	$animlinmarr = stringToStringArray($animlinm, " ");
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	for ($ist =($qseline-1); $ist>=0;  --$ist){
		int $indexarr = stringArrayFind( $seli[$ist], 0, $animlinmarr );
		stringArrayRemoveAtIndex($indexarr, $animlinmarr);
		stringArrayRemoveAtIndex($indexarr, $animlistarr);
		stringArrayRemoveAtIndex($indexarr, $animlienarr);
	}

	for ($tip = 0; $tip < size ($animlinmarr);++$tip){
		string $splitedResult[] = stringToStringArray($animlinmarr[$tip], "|");
		if (size($splitedResult) > 1)
			$animlinmarr[$tip] = $splitedResult[1];
	}

	string $finpada;
	for ($tp = 0; $tp < size ($animlinmarr);++$tp){
		string $padString = "0";
		string $prt = (string)($tp+1);
		if((size ($prt))<2)
			for($i=0;$i<(2-(size ($prt)));$i++){
				$padString=$padString+"0" ;
			}
		$finpada = $padString+($tp +1);
		$animlinmarr[$tp] = $finpada + "|" + $animlinmarr[$tp];
	}
	AppendUndo();
	setAttr -type "string" AnimAssistant.AnimationClipName (stringArrayToString($animlinmarr, " "));
	setAttr -type "string" AnimAssistant.StartFrame (stringArrayToString($animlistarr, " "));
	setAttr -type "string" AnimAssistant.EndFrame (stringArrayToString($animlienarr, " "));

	textScrollList -e -ra $animli;
	$animlinm = `getAttr AnimAssistant.AnimationClipName`;
	$animlinmarr = stringToStringArray($animlinm, " ");
	for ($ob in $animlinmarr){
		textScrollList -e -a $ob $animli;
	}
	if ($qannm != ""){

		textScrollList -e -ra $animli;
		string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
		string $filteredList[];
		string $aite[] = `textScrollList -q -ai $animli`;
		int $i = 0;
		for ($each in $aite){
			string $keyword_lower = `tolower $qannm`;
			string $each_lower = `tolower $each`;

			string $findMatch = `match $keyword_lower $each_lower `;
			if ($findMatch == $keyword_lower ){
				$filteredList[$i] = $each;
				$i++;
			}
		}
		textScrollList -edit -ra $animli;
		for ($each in $filteredList){
			textScrollList -edit -append $each $animli;
		}
	} else {
		textScrollList -e -ra $animli;
		$animlinm = `getAttr AnimAssistant.AnimationClipName`;
		$animlinmarr = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
	}
}



global proc FrameInst () {
	global string $framest;
	global string $frameen;
	float $sttr = `playbackOptions -q -min`;
	float $endtr = `playbackOptions -q -max`;
	textField -e -tx $sttr $framest;
	textField -e -tx $endtr $frameen;
}

global proc SetAnimationClip(string $name) {
	global string $framest;
	global string $frameen;
	global string $frameco;
	global string $animnm;
	global string $gPlayBackSlider;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	int $indexarr = stringArrayFind( $name, 0, $animlinmarr );
	textField -e -tx $animlistarr[$indexarr] $framest;
	textField -e -tx $animlienarr[$indexarr] $frameen;
	string $seli = `substitute ("_" + $animlistarr[$indexarr] + "-" + $animlienarr[$indexarr]) $name  ""`;
	string $nnam = "Unknown";
	string $splitedResult[] = stringToStringArray($seli, "|");
	if (size($splitedResult) > 1)
		$nnam = $splitedResult[1];
	textField -e -tx $nnam $animnm;
	$count = int($animlienarr[$indexarr]) - int($animlistarr[$indexarr]);
	text -e -l $count $frameco;
}

global proc SelectAnimClip () {
	global string $animli;
	string $objsfke[] = `textScrollList -q -si $animli`;
	if (size($objsfke) != 0) {
		SetAnimationClip($objsfke[0]);
	}
}

global proc FocusAnimClip () {
	global string $animli;
	string $objsfke[] = `textScrollList -q -si $animli`;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	int $indexarr = stringArrayFind( $objsfke[0], 0, $animlinmarr );
	currentTime -edit $animlistarr[$indexarr];
	playbackOptions -min ($animlistarr[$indexarr]) -max ($animlienarr[$indexarr]) ;
}


global proc ClearStField () {
	global string $framest;
	textField -e -tx "" $framest;

}

global proc ClearEnField () {
	global string $frameen;
	textField -e -tx "" $frameen;

}

global proc ClearNmField () {
	global string $animnm;
	textField -e -tx "" $animnm;

}

global proc ClearFlField () {
	global string $animli;
	global string $animfl;
	string $seli[] = `textScrollList -q -si $animli`;
	textField -e -tx "" $animfl;
	textScrollList -e -ra $animli;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	for ($ob in $animlinmarr){
		textScrollList -e -a $ob $animli;
	}

	for ($ti in $seli){
		textScrollList -e -si $ti  $animli;
	}
}

global proc ClearAllField () {
	global string $framest;
	global string $animnm;
	global string $frameen;
	textField -e -tx "" $framest;
	textField -e -tx "" $frameen;
	textField -e -tx "" $animnm;
}

global proc RenNmField () {

	global string $framest;
	global string $frameen;
	global string $animli;
	global string $animnm;
	global string $animfl;
	string $seli[] = `textScrollList -q -si $animli`;
	string $qannm = `textField -q -tx $animnm`;
	string $fannm = `textField -q -tx $animfl`;
	string $ststfr = `textField -q -tx $framest` ;
	string $stenfr = `textField -q -tx $frameen` ;
	int $qseline = `textScrollList -q -nsi $animli`;
	int $objsfik[] = `textScrollList -q -sii $animli`;
	string $objsfak[] = `textScrollList -q -si $animli`;

	if ($qannm != "" && $ststfr != "" && $stenfr != ""){
		int $frst = `textField -q -tx $framest`;
		int $fren = `textField -q -tx $frameen`;
		int $grex = `objExists "AnimAssistant"`;
		string $animlist;
		string $animlistarr[];
		string $animlien;
		string $animlienarr[];

		string $sellle = `textField -q -tx $animnm`;

		while ( $sellle != ( $sellle = `substitute " " $sellle "_"` ) );

		string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($animlinm, " ");
		int $indexarr = stringArrayFind( $objsfak[0], 0, $animlinmarr );


		$animlist = `getAttr AnimAssistant.StartFrame`;
		$animlistarr = stringToStringArray($animlist, " ");
		$animlien = `getAttr AnimAssistant.EndFrame`;
		$animlienarr = stringToStringArray($animlien, " ");
		$textFieldValue = `textField -q -tx $animnm`;

		for ($ist =($qseline-1); $ist>=0;  --$ist){
			int $indexarr = stringArrayFind( $seli[$ist], 0, $animlinmarr );
			stringArrayRemoveAtIndex($indexarr, $animlinmarr);
			stringArrayRemoveAtIndex($indexarr, $animlistarr);
			stringArrayRemoveAtIndex($indexarr, $animlienarr);
		}

		for ($tip = 0; $tip < size ($animlinmarr);++$tip){
			string $splitedResult[] = stringToStringArray($animlinmarr[$tip], "|");
			if (size($splitedResult) > 1)
				$animlinmarr[$tip] = $splitedResult[1];
		}

		stringArrayInsertAtIndex(($indexarr) , $animlinmarr, ($sellle + "_" + $frst + "-" + $fren));
		string $finpada;

		for ($tp = 0; $tp < size ($animlinmarr);++$tp){
			string $padString = "0";
			string $prt = (string)($tp+1);
			if((size ($prt))<2)
				for($i=0;$i<(2-(size ($prt)));$i++){
					$padString=$padString+"0" ;
				}
			$finpada = $padString+($tp +1);
			$animlinmarr[$tp] = $finpada + "|" + $animlinmarr[$tp];
		}
		AppendUndo();
		setAttr -type "string" AnimAssistant.AnimationClipName (stringArrayToString($animlinmarr, " "));
		stringArrayInsertAtIndex(($indexarr), $animlistarr, $frst);
		setAttr -type "string" AnimAssistant.StartFrame (stringArrayToString($animlistarr, " "));
		stringArrayInsertAtIndex(($indexarr), $animlienarr, $fren);
		setAttr -type "string" AnimAssistant.EndFrame (stringArrayToString($animlienarr, " "));


		textScrollList -e -ra $animli;
		$animlinm = `getAttr AnimAssistant.AnimationClipName`;
		$animlinmarr = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
	} else {
	}
	if ($fannm != ""){

		textScrollList -e -ra $animli;
		string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
		string $filteredList[];
		string $aite[] = `textScrollList -q -ai $animli`;
		int $i = 0;
		for ($each in $aite){
				   string $keyword_lower = `tolower $fannm`;
				   string $each_lower = `tolower $each`;
				   string $findMatch = `match $keyword_lower $each_lower `;
				   if ($findMatch == $keyword_lower ){
						$filteredList[$i] = $each;
						$i++;
				   }
		 }


		 textScrollList -edit -ra $animli;
		 for ($each in $filteredList){
			textScrollList -edit -append $each $animli;
		 }

	} else {
		textScrollList -e -ra $animli;
		$animlinm = `getAttr AnimAssistant.AnimationClipName`;
		$animlinmarr = stringToStringArray($animlinm, " ");
		for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
		}
	}
	textScrollList -e -sii ($objsfik[0]) $animli;

}

global proc moveAnimUP () {
	global string $animfl;
	global string $animli;
	string $fannm = `textField -q -tx $animfl`;
	string $objsall[] = `textScrollList -q -si $animli`;
	int $objssil[]= `textScrollList -q -sii $animli`;
	int $op;
	int $prevPos;
	int $prP[];
	if ($fannm == ""){
		for ($op=0;$op< `size $objssil`; ++$op){
			$prevPos = ( $objssil[$op] == 1 )?$objssil[$op]:($objssil[$op] - 1);
			$prP[$op] = $prevPos;
			string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
			string $animlist = `getAttr AnimAssistant.StartFrame`;
			string $animlien = `getAttr AnimAssistant.EndFrame`;
			string $animlinmarr[] = stringToStringArray($animlinm, " ");
			string $animlistarr[] = stringToStringArray($animlist, " ");
			string $animlienarr[] = stringToStringArray($animlien, " ");
			string $fsfr = $animlistarr[$objssil[$op]-1];
			string $enfr = $animlienarr[$objssil[$op]-1];
			string $nmfr = $animlinmarr[$objssil[$op]-1];
			stringArrayRemoveAtIndex(($objssil[$op]-1), $animlinmarr);
			stringArrayRemoveAtIndex(($objssil[$op]-1), $animlistarr);
			stringArrayRemoveAtIndex(($objssil[$op]-1), $animlienarr);


			stringArrayInsertAtIndex(($prevPos-1), $animlinmarr, $nmfr);
			stringArrayInsertAtIndex(($prevPos-1), $animlistarr, $fsfr);
			stringArrayInsertAtIndex(($prevPos-1), $animlienarr, $enfr);

			for ($tip = 0; $tip < size ($animlinmarr);++$tip){
				string $splitedResult[] = stringToStringArray($animlinmarr[$tip], "|");
				if (size($splitedResult) > 1)
					$animlinmarr[$tip] = $splitedResult[1];
			}

			for ($tp = 0; $tp < size ($animlinmarr);++$tp){
				string $padString = "0";
				string $prt = (string)($tp+1);
				if((size ($prt))<2)
					for($i=0;$i<(2-(size ($prt)));$i++){
						$padString=$padString+"0" ;
					}
					$finpada = $padString+($tp +1);
					$animlinmarr[$tp] = $finpada + "|" + $animlinmarr[$tp];
			}
			AppendUndo();
			setAttr -type "string" AnimAssistant.AnimationClipName (stringArrayToString($animlinmarr, " "));
			setAttr -type "string" AnimAssistant.StartFrame (stringArrayToString($animlistarr, " "));
			setAttr -type "string" AnimAssistant.EndFrame (stringArrayToString($animlienarr, " "));
			textScrollList -e -ra $animli;
			$animlinm = `getAttr AnimAssistant.AnimationClipName`;
			$animlinmarr = stringToStringArray($animlinm, " ");
			for ($ob in $animlinmarr){
				textScrollList -e -a $ob $animli;
			}
		}
		for ($bet in $prP){
			textScrollList -e -sii $bet  $animli;
		}
	}
}

global proc moveAnimDN () {

	global string $animfl;
	global string $animli;
	string $fannm = `textField -q -tx $animfl`;
	string $objsall[] = `textScrollList -q -si $animli`;
	int $objssil[]= `textScrollList -q -sii $animli`;
	int $nuit = `textScrollList -q -ni $animli`;
	int $op;
	int $prevPos;
	int $provPos;
	int $prP[];
	clear($prP);
	if ($fannm == ""){
		for ( $op = (`size $objssil` - 1); $op >= 0; --$op ){
			$prevPos = ( $objssil[$op] == 1 )?$objssil[$op]:($objssil[$op] - 1);
			$provPos = ( $objssil[$op] == 1 )?$objssil[$op]:($objssil[$op] + 1);
			$prP[$op] = $provPos;
			print $provPos;
			string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
			string $animlist = `getAttr AnimAssistant.StartFrame`;
			string $animlien = `getAttr AnimAssistant.EndFrame`;
			string $animlinmarr[] = stringToStringArray($animlinm, " ");
			string $animlistarr[] = stringToStringArray($animlist, " ");
			string $animlienarr[] = stringToStringArray($animlien, " ");
			string $fsfr = $animlistarr[$objssil[$op]-1];
			string $enfr = $animlienarr[$objssil[$op]-1];
			string $nmfr = $animlinmarr[$objssil[$op]-1];
			stringArrayRemoveAtIndex(($objssil[$op]-1), $animlinmarr);
			stringArrayRemoveAtIndex(($objssil[$op]-1), $animlistarr);
			stringArrayRemoveAtIndex(($objssil[$op]-1), $animlienarr);


			stringArrayInsertAtIndex(($objssil[$op]) , $animlinmarr, $nmfr);
			stringArrayInsertAtIndex(($objssil[$op]), $animlistarr, $fsfr);
			stringArrayInsertAtIndex(($objssil[$op]), $animlienarr, $enfr);

			for ($tip = 0; $tip < size ($animlinmarr);++$tip) {
				string $splitedResult[] = stringToStringArray($animlinmarr[$tip], "|");
				if (size($splitedResult) > 1)
					$animlinmarr[$tip] = $splitedResult[1];
			}

			for ($tp = 0; $tp < size ($animlinmarr);++$tp){
				string $padString = "0";
				string $prt = (string)($tp+1);
				if((size ($prt))<2)
				for($i=0;$i<(2-(size ($prt)));$i++){
					$padString=$padString+"0" ;
				}
				$finpada = $padString+($tp +1);
				$animlinmarr[$tp] = $finpada + "|" + $animlinmarr[$tp];
			}
			AppendUndo();
			setAttr -type "string" AnimAssistant.AnimationClipName (stringArrayToString($animlinmarr, " "));
			setAttr -type "string" AnimAssistant.StartFrame (stringArrayToString($animlistarr, " "));
			setAttr -type "string" AnimAssistant.EndFrame (stringArrayToString($animlienarr, " "));
			textScrollList -e -ra $animli;
			$animlinm = `getAttr AnimAssistant.AnimationClipName`;
			$animlinmarr = stringToStringArray($animlinm, " ");
			for ($ob in $animlinmarr){
				textScrollList -e -a $ob $animli;
			}
		}
		for ($bet in $prP){
			if ($bet <= $nuit){
				if ($bet == 1){
					textScrollList -e -sii ($bet+1)  $animli;
				} else {
					textScrollList -e -sii $bet  $animli;
				}
			}
		}
	}
}

global proc AnimExporter () {
	string $singleFilter = "Anim Assistant File (*.txt)";
	string $filePath[] = `fileDialog2 -fileFilter $singleFilter -dialogStyle 2`;
	if (size($filePath) == 0)
		return;
	int $filedId = `fopen ($filePath[0]) "w"` ;

	string $finfo = `getAttr AnimAssistant.AnimationClipName`;
	string $animlinmarr[] = stringToStringArray($finfo, " ");
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlienarr[] = stringToStringArray($animlien, " ");
	for ($it=0;$it<size($animlinmarr);++$it){
		string $splitedResult[] = stringToStringArray($animlinmarr[$it], "|");
		if (size($splitedResult) > 1)
			$animlinmarr[$it] = $splitedResult[1];
		string $seli = `substitute ("_" + ($animlistarr[$it]) + "-" + ($animlienarr[$it])) $animlinmarr[$it] ""`;
		fprint $filedId ($animlistarr[$it] + " " + $animlienarr[$it] + " " + $seli + "\r\n");
	}

	fclose $filedId ;
}

global proc AnimExporterSelected () {
	string $singleFilter = "Anim Assistant File (*.txt)";
	string $filePath[] = `fileDialog2 -fileFilter $singleFilter -dialogStyle 2`;
	if (size($filePath) == 0)
		return;
	int $filedId = `fopen ($filePath[0]) "w"` ;

	global string $animli;
	string $seli[] = `textScrollList -q -si $animli`;
	string $finfo = `getAttr AnimAssistant.AnimationClipName`;
	string $animlinmarr[] = stringToStringArray($finfo, " ");
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlienarr[] = stringToStringArray($animlien, " ");
	for ($it=0;$it<size($animlinmarr);++$it){
		int $indexarr = stringArrayFind( $animlinmarr[$it], 0, $seli );
		if ($indexarr >= 0 || size($seli) == 0) {
			string $splitedResult[] = stringToStringArray($animlinmarr[$it], "|");
			if (size($splitedResult) > 1){
				$animlinmarr[$it] = $splitedResult[1];
				string $seli = `substitute ("_" + ($animlistarr[$it]) + "-" + ($animlienarr[$it])) $animlinmarr[$it] ""`;
				fprint $filedId ($animlistarr[$it] + " " + $animlienarr[$it] + " " + $seli + "\r\n");
			}
		}
	}

	fclose $filedId ;
}

global proc AnimImporter () {
	global string $animli;
	string $dirName = dirname(`file -q -sn`) + "/*.txt";
	string $filePath = `fileDialog -dm $dirName`;
	if (size($filePath) == 0)
		return;
	int $filedId = `fopen ($filePath) "r"` ;
	string $dataArray[] ;
	string $animnmArr[];
	string $animstArr[];
	string $animenArr[];
	clear ($dataArray);
	int $exTest = `filetest -r $filePath`;
	string $nextLine = `fgetline $filedId` ;
	int $skipFirstLine;
	if ($exTest == 1){
		CreateIfNotExistNodeAttribute();
		while (size($nextLine) > 0) {
			string $cleanLine = strip($nextLine) ;
			$dataArray[size($dataArray)] = $cleanLine ;
			$nextLine = `fgetline $filedId` ;
		}
		if($skipFirstLine) stringArrayRemoveAtIndex(0,$dataArray) ;

		for ($ope=0; $ope<(size($dataArray));++$ope){
			string $tempostring[];
			int $ttttt = `tokenize $dataArray[$ope] " " $tempostring`;
			$animnmArr[$ope] = $tempostring[2] + "_" + $tempostring[0] + "-" + $tempostring[1];
			$animstArr[$ope] = $tempostring[0];
			$animenArr[$ope] = $tempostring[1];
		}

		for ($tp = 0; $tp < size ($animnmArr);++$tp){
			string $padString = "0";
			string $prt = (string)($tp+1);
			if((size ($prt))<2)
			for($i=0;$i<(2-(size ($prt)));$i++){

			$padString=$padString+"0" ;
			}
			$finpada = $padString+($tp +1);
			$animnmArr[$tp] = $finpada + "|" + $animnmArr[$tp];


		}

		string $annnm = stringArrayToString ($animnmArr, " ");
		string $annst = stringArrayToString ($animstArr, " ");
		string $annen = stringArrayToString ($animenArr, " ");
		AppendUndo();
		setAttr -type "string" AnimAssistant.AnimationClipName $annnm;
		setAttr -type "string" AnimAssistant.StartFrame $annst;
		setAttr -type "string" AnimAssistant.EndFrame $annen;

		textScrollList -e -ra $animli;
		for ($obg in $animnmArr){
		textScrollList -e -a $obg $animli;

		}
	}
}

global proc AnimLiUpdate (){
	global string $animli;
	int $grex = `objExists "AnimAssistant"`;
	if ($grex == 1){
		string $finfo = `getAttr AnimAssistant.AnimationClipName`;
		string $animlinmarr[] = stringToStringArray($finfo, " ");
		textScrollList -e -ra $animli;
		for ($obg in $animlinmarr){
			textScrollList -e -a $obg $animli;
		}
	} else {
		textScrollList -e -ra $animli;
	}
	UpdateCamerasList();
}

global proc AnimColorRange () {
	global string $animli;
	global string $animnm;
	int $objsfik[] = `textScrollList -q -sii $animli`;
	int $anlesit = `textScrollList -q -nsi $animli`;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	float $colorP[] = `colorSliderGrp -q -rgb AnimationColor`;
	string $obli[] = `ls -sl -l`;

	string $objsfke[] = `textScrollList -q -si $animli`;
	int $indexarr = stringArrayFind( $objsfke[0], 0, $animlinmarr );
	  for ($zip = 0; $zip < $anlesit; ++$zip){
		int $indexarr = stringArrayFind( $objsfke[$zip], 0, $animlinmarr );
		int $stfr = (int)$animlistarr[$indexarr];
		int $enfr = (int)$animlienarr[$indexarr];


			for ($obi=0; $obi<(size($obli)); ++$obi) {
				float $ranum = `rand 0 999`;
				string $sranum = (string)$ranum;
				string $stranum = `substitute "\\." $sranum "_"`;
				string $ranname = "curveColor_" + $stranum;
				string $liscur[] = `listAttr -st "curveColor_*" $obli[$obi]`;
				string $shnm = `match "[^|\\]*$" $obli[$obi]`;
				for ($im in $liscur){
					cutKey -t $stfr -attribute $im -option keys -clear $obli[$obi];
					cutKey -t $enfr -attribute $im -option keys -clear $obli[$obi];
					float $qkeysak[] = `keyframe -q ($obli[$obi]+ "." + $im)`;
					float $qkeysa = `keyframe -q -kc ($obli[$obi]+ "." + $im)`;
					if ($qkeysak[0]<0 && $qkeysa<=1) {
					   deleteAttr -attribute $im $obli[$obi];

					}
				}

				addAttr -longName $ranname -k true -h true $obli[$obi];

				setKeyframe -t $stfr ($obli[$obi] + "." + $ranname);
				setKeyframe -t $enfr ($obli[$obi] + "." + $ranname);

				string $buffer[] ;
				tokenize $shnm ":" $buffer ;
				string $newName = $buffer[size($buffer)-1] ;

				setAttr ($newName + "_" + $ranname + ".curveColor") -type double3 $colorP[0] $colorP[1] $colorP[2] ;
				setAttr ($newName + "_" + $ranname + ".useCurveColor") 1;
				addAttr -longName ($ranname+"_red") -k true -h true $obli[$obi];
				setKeyframe -t -1 ($obli[$obi] + "." + $ranname +"_red");
				setAttr ($newName + "_" + $ranname + "_red.curveColor") -type double3 1 0 0 ;
				setAttr ($newName + "_" + $ranname  + "_red.useCurveColor") 1;
			}
	}

	 int $filex = `objExists "AnimAttr"`;
	  if ($filex == 0) {
		  itemFilterAttr -bn "curveColor_*" -neg true AnimAttr;
		  outlinerEditor -e -attrFilter "AnimAttr" graphEditor1OutlineEd;

	  } else {
		  outlinerEditor -e -attrFilter "AnimAttr" graphEditor1OutlineEd;
	  }


}

global proc AnimColorFill () {
	global string $animli;
	global string $animnm;
	int $objsfik[] = `textScrollList -q -sii $animli`;
	int $anlesit = `textScrollList -q -nsi $animli`;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	float $colorP[] = `colorSliderGrp -q -rgb AnimationColor`;
	string $obli[] = `ls -sl -l`;

	string $objsfke[] = `textScrollList -q -si $animli`;
	int $indexarr = stringArrayFind( $objsfke[0], 0, $animlinmarr );

	for ($zip = 0; $zip < $anlesit; ++$zip){
		int $indexarr = stringArrayFind( $objsfke[$zip], 0, $animlinmarr );
		int $stfr = (int)$animlistarr[$indexarr];
		int $enfr = (int)$animlienarr[$indexarr];


			for ($obi=0; $obi<(size($obli)); ++$obi) {
				float $ranum = `rand 0 999`;
				string $sranum = (string)$ranum;
				string $stranum = `substitute "\\." $sranum "_"`;
				string $ranname = "curveColor_" + $stranum;
				string $liscur[];
				clear($liscur);
				$liscur = `listAttr -st "curveColor_*" $obli[$obi]`;
				string $shnm = `match "[^|\\]*$" $obli[$obi]`;
				for ($im in $liscur){
					int $am;
					for ($am=$stfr; $am<=$enfr; ++$am){
						cutKey -t $am -attribute $im -option keys -clear $obli[$obi];

					}

					 float $qkeysak[] = `keyframe -q ($obli[$obi]+ "." + $im)`;
					float $qkeysa = `keyframe -q -kc ($obli[$obi]+ "." + $im)`;
					if ($qkeysak[0]<0 && $qkeysa<=1) {
					   deleteAttr -attribute $im $obli[$obi];

					}
				}

				addAttr -longName $ranname -k true -h true $obli[$obi];
				int $om;
				for ($om=$stfr; $om<=$enfr; ++$om){
					setKeyframe -t $om ($obli[$obi] + "." + $ranname);
				}

				string $buffer[] ;
				tokenize $shnm ":" $buffer ;
				string $newName = $buffer[size($buffer)-1] ;

				setAttr ($newName + "_" + $ranname + ".curveColor") -type double3 $colorP[0] $colorP[1] $colorP[2] ;
				setAttr ($newName + "_" + $ranname + ".useCurveColor") 1;
				addAttr -longName ($ranname+"_red") -k true -h true $obli[$obi];
				setKeyframe -t -1 ($obli[$obi] + "." + $ranname +"_red");
				setAttr ($newName + "_" + $ranname + "_red.curveColor") -type double3 1 0 0 ;
				setAttr ($newName + "_" + $ranname  + "_red.useCurveColor") 1;

			}
	}

	int $filex = `objExists "AnimAttr"`;
	  if ($filex == 0) {
		  itemFilterAttr -bn "curveColor_*" -neg true AnimAttr;
		  outlinerEditor -e -attrFilter "AnimAttr" graphEditor1OutlineEd;

	  } else {
		  outlinerEditor -e -attrFilter "AnimAttr" graphEditor1OutlineEd;
	  }

}

global proc AnimColorClear () {
	global string $animli;
	global string $animnm;
	int $objsfik[] = `textScrollList -q -sii $animli`;
	int $anlesit = `textScrollList -q -nsi $animli`;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	float $colorP[] = `colorSliderGrp -q -rgb AnimationColor`;
	string $obli[] = `ls -sl -l`;

	string $objsfke[] = `textScrollList -q -si $animli`;
	int $indexarr = stringArrayFind( $objsfke[0], 0, $animlinmarr );


	for ($zip = 0; $zip < $anlesit; ++$zip){
		int $indexarr = stringArrayFind( $objsfke[$zip], 0, $animlinmarr );
		int $stfr = (int)$animlistarr[$indexarr];
		int $enfr = (int)$animlienarr[$indexarr];


			for ($obi=0; $obi<(size($obli)); ++$obi) {
				float $ranum = `rand 0 999`;
				string $sranum = (string)$ranum;
				string $stranum = `substitute "\\." $sranum "_"`;
				string $ranname = "curveColor_" + $stranum;
				string $liscur[] = `listAttr -st "curveColor_*" $obli[$obi]`;
				string $shnm = `match "[^|\\]*$" $obli[$obi]`;
				for ($im in $liscur){
					cutKey -t $stfr -attribute $im -option keys -clear $obli[$obi];
					cutKey -t $enfr -attribute $im -option keys -clear $obli[$obi];
					float $qkeysa[] = `keyframe -q ($obli[$obi]+ "." + $im)`;
					if (!$qkeysa[0]) {
					   deleteAttr -attribute $im $obli[$obi];

					}
				}


			}
	}


}

global proc AnimColorFillClear () {

global string $animli;
	global string $animnm;
	int $objsfik[] = `textScrollList -q -sii $animli`;
	int $anlesit = `textScrollList -q -nsi $animli`;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	float $colorP[] = `colorSliderGrp -q -rgb AnimationColor`;
	string $obli[] = `ls -sl -l`;

	string $objsfke[] = `textScrollList -q -si $animli`;
	int $indexarr = stringArrayFind( $objsfke[0], 0, $animlinmarr );


	for ($zip = 0; $zip < $anlesit; ++$zip){
		int $indexarr = stringArrayFind( $objsfke[$zip], 0, $animlinmarr );
		int $stfr = (int)$animlistarr[$indexarr];
		int $enfr = (int)$animlienarr[$indexarr];


			for ($obi=0; $obi<(size($obli)); ++$obi) {
				float $ranum = `rand 0 999`;
				string $sranum = (string)$ranum;
				string $stranum = `substitute "\\." $sranum "_"`;
				string $ranname = "curveColor_" + $stranum;
				string $liscur[];
				clear($liscur);
				$liscur = `listAttr -st "curveColor_*" $obli[$obi]`;
				string $shnm = `match "[^|\\]*$" $obli[$obi]`;
				for ($im in $liscur){
					int $am;
					for ($am=$stfr; $am<=$enfr; ++$am){
						cutKey -t $am -attribute $im -option keys -clear $obli[$obi];

					}

					float $qkeysa[] = `keyframe -q ($obli[$obi]+ "." + $im)`;
					if (!$qkeysa[0]) {
					   deleteAttr -attribute $im $obli[$obi];

					}
				}




			}
	}

	}


global proc AnimColorClearAll () {

	global string $animli;
	global string $animnm;
	int $objsfik[] = `textScrollList -q -sii $animli`;
	int $anlesit = `textScrollList -q -nsi $animli`;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	float $colorP[] = `colorSliderGrp -q -rgb AnimationColor`;
	string $obli[] = `ls -sl -l`;

	string $objsfke[] = `textScrollList -q -si $animli`;
	int $indexarr = stringArrayFind( $objsfke[0], 0, $animlinmarr );

				for ($obi=0; $obi<(size($obli)); ++$obi) {

				string $liscur[];
				clear($liscur);
				$liscur = `listAttr -st "curveColor_*" $obli[$obi]`;
				string $shnm = `match "[^|\\]*$" $obli[$obi]`;
				for ($im in $liscur){
					deleteAttr -attribute $im $obli[$obi];
				}
			}
	}

global proc AnimOffset () {
	global string $animfl;
	global string $animli;
	global string $animnm;
	global string $framest;
	global string $frameen;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	string $fannm = `textField -q -tx $animfl`;
	int $site[] = `textScrollList -q -sii $animli`;
	int $ait = `textScrollList -q -ni $animli`;
	int $ststfr = `textField -q -tx $framest` ;
	int $stenfr = `textField -q -tx $frameen` ;
	string $objsfak[] = `textScrollList -q -si $animli`;
	int $indexarr = stringArrayFind( $objsfak[0], 0, $animlinmarr );
	int $diff = $stenfr - (int)$animlienarr[$indexarr];
	int $anlesit = `textScrollList -q -nsi $animli`;

	$animlinmarr[$indexarr] = `substitute ("_" + ($animlistarr[$indexarr]) + "-" + ($animlienarr[$indexarr])) $animlinmarr[$indexarr] ""`;
	$animlienarr[$indexarr] = $stenfr;
	$animlinmarr[$indexarr] = $animlinmarr[$indexarr] + "_" + $animlistarr[$indexarr] + "-"  + $animlienarr[$indexarr];
	if ($anlesit == 1){
		for ($it=0;$it<size($animlinmarr);++$it){;
		$animlinmarr[$it] = `substitute ("_" + ($animlistarr[$it]) + "-" + ($animlienarr[$it])) $animlinmarr[$it] ""`;
		}
		for ($bic = ($indexarr+1); $bic <(size($animlinmarr)); ++$bic){

			$animlienarr[$bic] = (int)$animlienarr[$bic] + $diff;
			$animlistarr[$bic] = (int)$animlistarr[$bic] + $diff;
		}
		for ($ot=0;$ot<size($animlinmarr);++$ot){
		$animlinmarr[$ot] = $animlinmarr[$ot] + "_" + $animlistarr[$ot] + "-"  + $animlienarr[$ot];
		}
	} else if ($anlesit > 1) {
			for ($bac = 1; $bac < $anlesit; ++$bac) {
			int $indexorr = stringArrayFind( $objsfak[$bac], 0, $animlinmarr );
			$animlinmarr[$indexorr] = `substitute ("_" + ($animlistarr[$indexorr]) + "-" + ($animlienarr[$indexorr])) $animlinmarr[$indexorr] ""`;
			$animlienarr[$indexorr] = (int)$animlienarr[$indexorr] + $diff;
			$animlistarr[$indexorr] = (int)$animlistarr[$indexorr] + $diff;
			$animlinmarr[$indexorr] = $animlinmarr[$indexorr] + "_" + $animlistarr[$indexorr] + "-"  + $animlienarr[$indexorr];
		}
	}

	AppendUndo();
	setAttr -type "string" AnimAssistant.AnimationClipName (stringArrayToString($animlinmarr, " "));
	setAttr -type "string" AnimAssistant.StartFrame (stringArrayToString($animlistarr, " "));
	setAttr -type "string" AnimAssistant.EndFrame (stringArrayToString($animlienarr, " "));

	if ($fannm != ""){
			textScrollList -e -ra $animli;
			string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
			string $animlinmarr[] = stringToStringArray($animlinm, " ");
			for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
			}
			string $filteredList[];
			string $aite[] = `textScrollList -q -ai $animli`;
			int $i = 0;
			for ($each in $aite){
					   string $keyword_lower = `tolower $fannm`;
					   string $each_lower = `tolower $each`;

					   string $findMatch = `match $keyword_lower $each_lower `;
					   if ($findMatch == $keyword_lower ){
							   $filteredList[$i] = $each;

							   $i++;
					   }
			 }
			textScrollList -edit -ra $animli;
			 for ($each in $filteredList){
					  textScrollList -edit -append $each $animli;
			 }

		} else {
		textScrollList -e -ra $animli;
			$animlinm = `getAttr AnimAssistant.AnimationClipName`;
			$animlinmarr = stringToStringArray($animlinm, " ");
			for ($ob in $animlinmarr){
			textScrollList -e -a $ob $animli;
			}
		}
		textScrollList -e -sii ($site[0]) $animli;

}

global proc ExptoTOGame () {

	global string $animfl;
	global string $animli;
	global string $animnm;
	global string $framest;
	global string $frameen;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	string $objsfak[] = `textScrollList -q -ai $animli`;
	int $ait = `textScrollList -q -ni $animli`;
	int $indexarr = stringArrayFind( $objsfak[0], 0, $animlinmarr );

	for ($tip = 0; $tip < size ($animlinmarr);++$tip){
		string $splitedResult[] = stringToStringArray($animlinmarr[$tip], "|");
		if (size($splitedResult) > 1)
			$animlinmarr[$tip] = $splitedResult[1];
		$animlinmarr[$tip] = `substitute ("_" + ($animlistarr[$tip]) + "-" + ($animlienarr[$tip])) $animlinmarr[$tip] ""`;
	}

	for ($zi = 0; $zi < $ait; ++$zi){
		gameExp_AddNewAnimationClip 1;
		setAttr("gameExporterPreset2.animClips["+$zi+"].animClipStart") ((float)$animlistarr[$zi]);
		setAttr("gameExporterPreset2.animClips["+$zi+"].animClipEnd") ((float)$animlienarr[$zi]);
		setAttr("gameExporterPreset2.animClips["+$zi+"].animClipName") -type "string" $animlinmarr[$zi];

	}

gameExp_CreateExportTypeUIComponents();


}

global proc StoreTakes () {
	global string $animfl;
	global string $animli;
	global string $animnm;
	global string $framest;
	global string $frameen;
	string $animlist = `getAttr AnimAssistant.StartFrame`;
	string $animlien = `getAttr AnimAssistant.EndFrame`;
	string $animlinm = `getAttr AnimAssistant.AnimationClipName`;
	string $animlistarr[] = stringToStringArray($animlist, " ");
	string $animlienarr[] = stringToStringArray($animlien, " ");
	string $animlinmarr[] = stringToStringArray($animlinm, " ");
	string $objsfak[] = `textScrollList -q -ai $animli`;
	int $ait = `textScrollList -q -ni $animli`;
	int $indexarr = stringArrayFind( $objsfak[0], 0, $animlinmarr );

	for ($tip = 0; $tip < size ($animlinmarr);++$tip){
		string $splitedResult[] = stringToStringArray($animlinmarr[$tip], "|");
		if (size($splitedResult) > 1)
			$animlinmarr[$tip] = $splitedResult[1];
		$animlinmarr[$tip] = `substitute ("_" + ($animlistarr[$tip]) + "-" + ($animlienarr[$tip])) $animlinmarr[$tip] ""`;

	}
	FBXExportSplitAnimationIntoTakes -c;
	for ($zi = 0; $zi < $ait; ++$zi){
		FBXExportSplitAnimationIntoTakes -v $animlinmarr[$zi] ((float)$animlistarr[$zi]) ((float)$animlienarr[$zi]);


	}
}


